packages/guides-restructured-text/src/RestructuredText/Parser/DocumentParserContext.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DocumentRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineMarkupRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/ParagraphRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/ParagraphRuleTest.php
The new rule allows us to use the spanparser together with other productions in the same context. Just like the paragraph parser it should be applied as last option. This should simplify the processing of table contents and other elements that allow body elements in their content.
=> Introduce InlineMarkup rule

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DocumentRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/ListRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/RuleContainer.php, packages/guides-restructured-text/tests/unit/Parser/Productions/AbstractRuleTest.php, packages/guides-restructured-text/tests/unit/Parser/Productions/CollectAllRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/ListRuleTest.php, packages/guides-restructured-text/tests/unit/Parser/Productions/ParagraphRuleTest.php, packages/guides/resources/config/html.php, packages/guides/resources/template/guides/list-item.html.twig, packages/guides/resources/template/guides/list.html.twig, packages/guides/src/Nodes/ListItemNode.php, packages/guides/src/Nodes/ListNode.php, packages/guides/src/Nodes/Lists/ListItem.php, packages/guides/src/Nodes/ParagraphNode.php, packages/guides/tests/unit/Nodes/ListItemNodeTest.php, tests/tests/enumerated/enumerated.html, tests/tests/list-alternate-syntax/list-alternate-syntax.html, tests/tests/list-alternate-syntax/list-alternate-syntax.rst, tests/tests/list-dash/list-dash.html, tests/tests/list-indented/list-indented.html, tests/tests/list-mix/list-mix.html
Parsing lists is now done using the new producer rules. This makes the process more flexible and allows us to configure what we need.
The code should now be more readable and easier to understand.
=> Refactor list parsing

packages/guides-restructured-text/src/RestructuredText/Parser/DocumentParserContext.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/TitleRule.php, tests/tests/titles-overlined/titles-overlined.html
TYPO3 docs usually have the Document title between two lines of `=` each
=> Nest overlined or framed titles different from underlined ones

packages/guides-restructured-text/src/RestructuredText/Directives/Directive.php, packages/guides-restructured-text/src/RestructuredText/Parser/Directive.php, packages/guides-restructured-text/src/RestructuredText/Parser/DirectiveOption.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveRule.php, packages/guides-restructured-text/tests/unit/Parser/DummyDirective.php, packages/guides-restructured-text/tests/unit/Parser/DummyNode.php, packages/guides-restructured-text/tests/unit/Parser/Productions/DirectiveRuleTest.php, tests/tests/figure-multiline-alt/figure-multiline-alt.html
directive options are basically field lists:
https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#directives 'Directive options are indicated using field lists; the field names and contents are directive-specific.'
Field list options can have multiple lines:
https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#field-lists
=> Enable multiline directive options

tests/tests/titles-auto/titles-auto.rst, tests/tests/titles/titles.rst
"A blank line after a title is optional. All text blocks up to the next title of the same or higher level are included in a section (or subsection, etc.)."
The tests where the blank line before the title was missing are not correct in my eyes. At least in our files we do not have such titles.
https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#sections
=> Correct title / section tests

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveRule.php, tests/tests/directive-ignore-case/directive-ignore-case.html
"Directives are indicated by an explicit markup start (".. ") followed by the directive type, two colons, and whitespace (together called the "directive marker"). Directive types are **case-insensitive single words**" https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#directives
=> Ignore case in directive name

packages/guides-restructured-text/src/RestructuredText/Directives/Image.php, packages/guides/src/RenderContext.php, packages/guides/src/Twig/AssetsExtension.php
The image path set in the directive is transformed into the absolute path on disk. This will help to locate it in the origin filesystem during rendering.
fixes #234
=> Fix image handling

packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlock.php, packages/guides-restructured-text/src/RestructuredText/Parser/Buffer.php, packages/guides-restructured-text/src/RestructuredText/Parser/DocumentParserContext.php, packages/guides-restructured-text/src/RestructuredText/Parser/LinesIterator.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/DirectiveRuleTest.php, packages/guides/src/Nodes/CodeNode.php, packages/guides/tests/unit/Nodes/CodeNodeTest.php, phpunit.xml.dist, tests/tests/code-block-diff/code-block-diff.html, tests/tests/code-block-indented-in-admonition/code-block-indented-in-admonition.html, tests/tests/code-block-indented-in-admonition/code-block-indented-in-admonition.rst, tests/tests/code-block-indented/code-block-indented.html, tests/tests/code-block-indented/code-block-indented.rst, tests/tests/code/code.html
Expecially in code blocks the first line of the directive content can have more indentation then the following ones. Overall this is true for all directives.
The general rule is that a directive ends when the indentation level of the directive declaration is found or when the file ends.
=> Directive ends on complete unindent

packages/guides/examples/render_docs.php, packages/guides/src/Handlers/CompileDocumentsCommand.php, packages/guides/src/Handlers/CompileDocumentsHandler.php
The command and handler are extremely simple, but makes the usage API of this library a bit more tidy (the service generating the docs now only needs the `CommandBus`, instead of `CommandBus`+`Compiler`).
=> Add CompileDocumentsCommand

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/GridTableRule.php, tests/Functional/tests/table-grid/table-grid.html, tests/Functional/tests/table-grid/table-grid.rst
A minor typo meant grid tables didn't end correctly, causing many subsequent lines to be considered as part of the table. This caused 646 random errors while rendering the Symfony documentation (as the first 2 characters of each subsequent line was stripped, this created weird reSt syntax for the rest of the parser to parse).
Fixes #253
=> Fix grid table end condition

Makefile, packages/guides/src/Renderer/DefaultTypeRendererFactory.php, packages/guides/src/Renderer/LatexTypeRenderer.php, packages/guides/src/Setup/QuickStart.php, tests/Integration/IntegrationTest.php, tests/Integration/tests/index/expected/index.html, tests/Integration/tests/sometest/index.rst
- clean up temp directories after general test runs
- introduce `make cleanup-tests` command
- ignore empty lines and trim lines before comparison
=> Refactor Integration Tests

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DefinitionListRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/DefinitionListRuleTest.php, tests/Integration/tests/toctree/expected/index.html, tests/Integration/tests/toctree/expected/subfolder/index.html, tests/Integration/tests/toctree/input/index.rst, tests/Integration/tests/toctree/input/page1.rst, tests/Integration/tests/toctree/input/page2.rst, tests/Integration/tests/toctree/input/subfolder/index.rst, tests/Integration/tests/toctree/input/subfolder/subpage1.rst, tests/Integration/tests/toctree/input/subfolder/subpage2.rst
It was treated as part of the definition list, ignoring its a directive
resolves #286
=> Make a directive end a definition list

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/DirectiveRuleTest.php, tests/Integration/tests/toctree/expected/index.html, tests/Integration/tests/toctree/expected/subfolder2/index.html, tests/Integration/tests/toctree/input/index.rst, tests/Integration/tests/toctree/input/subfolder2/index.rst, tests/Integration/tests/toctree/input/subfolder2/subpage1.rst, tests/Integration/tests/toctree/input/subfolder2/subpage2.rst
TYPO3 Documentation uses this to allign a directive and its content, Sphinx allows it:
```
..  toctree::
subpage1
subpage2
vs
.. toctree::
subpage1
subpage2
```
=> Allow multiple whitespace in directive

packages/guides-cli/.gitattributes, packages/guides-graphs/.gitattributes, packages/guides-markdown/.gitattributes, packages/guides-restructured-text/.gitattributes, packages/guides/.gitattributes
To make the composer packages a bit smaller, we should not export tests, docs etc.
=> Add attributes to ignore directories for export

composer.lock
* doctrine/instantiator (1.5.0 => 2.0.0)
* league/uri (6.7.2 => 6.8.0)
* netresearch/jsonmapper (v4.1.0 => v4.2.0)
* nette/utils (v3.2.9 => v4.0.0)
* phpdocumentor/guides (dev-main 6052e7a => dev-main 40e5adc)
* phpdocumentor/guides-cli (dev-main 34771ca => dev-main bb90619)
* phpdocumentor/guides-graphs (dev-main 1c87005 => dev-main 556847e)
* phpdocumentor/guides-restructured-text (dev-main a43310a => dev-main ebe40f9)
* phpdocumentor/guides-symfony (dev-main 282ca52 => dev-main ce8a0b1)
* phpspec/prophecy (v1.16.0 => v1.17.0)
* phpspec/prophecy-phpunit (v2.0.1 => v2.0.2)
* phpstan/phpdoc-parser (1.16.1 => 1.20.0)
* phpunit/phpunit (9.6.6 => 9.6.7)
* psr/cache (1.0.1 => 3.0.0)
* psr/http-message (1.0.1 => 1.1)
* rector/rector (0.15.23 => 0.15.25)
* spatie/array-to-xml (2.17.1 => 3.1.5) …
=> Bump locked dependencies

packages/guides-theme-bootstrap/composer.json
In its current state, the package does not contain any source code, so it does not really depend on a certain PHP version or specific packages. Also, autoloading does not make sense without code that could be autoloaded.
=> Removed all dependencies from the phpdocumentor/guides-theme-bootstrap package

packages/guides-restructured-text/tests/unit/Parser/SpanParserTest.php
This was changed because of a bug in the old coding standard. Let's change it back.
=> Fix intersection type spacing

packages/guides-restructured-text/src/RestructuredText/Directives/RubricDirective.php, packages/guides-symfony/resources/config/guides-restructured-text.php, packages/guides-symfony/src/DependencyInjection/Compiler/NodeRendererPass.php, packages/guides/resources/template/html/guides/body/rubric.html.twig, packages/guides/src/Nodes/RubricNode.php, tests/Functional/tests/rubric/rubric.html, tests/Functional/tests/rubric/rubric.rst
The general structure of directives can - in most cases - be saved into a general node type. 
A directive consists of a type, an argument, one or several options and content. the content can be in the form of nodes or plain text (for example code nodes)
I demonstrate usage of a DirectiveNode by introducing the rubric directive that was still missing. We can possibly replace many of the other nodes for directives with a general directive node.
In Sphinx there are rules for each directive what and how many of each kind of data it accepts. We might want to model that in future. Right now non-expected content is ignored.
The `:class:` option is one that can be added to all directives and it has the same effect like setting the class with the class directive. So I saved the class option in the …
=> Introduce the rubric directive

packages/guides/resources/template/html/guides/body/toc/toc-item.html.twig, packages/guides/resources/template/html/guides/body/toc/toc-level.html.twig, packages/guides/resources/template/html/guides/body/toc/toc.html.twig, tests/Integration/IntegrationTest.php, tests/Integration/tests/toctree-simple/expected/index.html, tests/Integration/tests/toctree-titlesonly/expected/index.html, tests/Integration/tests/toctree/expected/index.html, tests/Integration/tests/toctree/expected/subfolder2/index.html, tests/Integration/tests/toctree/input/page1.rst, tests/Integration/tests/toctree/input/page2.rst, tests/Integration/tests/toctree/input/skip
This library has the same issue as doctrine/rst-parser, where each toctree is assumed to be `:titlesonly:` and no sub-section titles are rendered. Although we are not using it in the Symfony documentation, we do have a test for this in our test suite somehow.
Lina has started a PR in the past to fix this for the Doctrine parser (https://github.com/doctrine/rst-parser/pull/199), we might reuse the logic from that PR to fix this test in the future.
Meanwhile, I've already made some minor improvements:
* Use relative paths as test name, this makes it easy to filter data sets (e.g. `./vendor/bin/phpunit tests/Integration/IntegrationTest.php --filter testHtmlIntegration@toctree`, currently "toctree" must be the full local path)
* Remove the `spaceless` tag from the template. This tag is …
=> Some toctree improvements + add skipped test for non-titlesonly toctrees

deptrac.packages.yaml, packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/FigureDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ImageDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/MetaDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ReplaceDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/TitleDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ToctreeDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/UmlDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/WrapDirective.php, packages/guides-restructured-text/tests/unit/Parser/Productions/DirectiveRuleTest.php, packages/guides-symfony/resources/config/guides-restructured-text.php
All Directives should end on "Directive" as we discussed in the code sprint
=> Unify Directive Naming

tests/Functional/FunctionalTest.php, tests/Functional/tests/titles-auto/titles-auto.html, tests/Integration/IntegrationTest.php
As we're using incomplete tests as a living todo list, I think it's good to also check whether such tests still fail.
This PR changes the functional and integration test to always run the tests and mark as incomplete only if there are errors. If there are no errors, but the test is skipped, it marks the test as failed.
As you see, this already discovered one skipped test that we have fixed in the past months :)
=> Fail incomplete tests that pass

composer.lock, packages/guides-restructured-text/composer.json, psalm-baseline.xml
guides-rstructured-text required "doctrine/lexer": "^3.0", while guides require  "doctrine/lexer": "^2.1". Tests only work with ^2.1 so use require it in both packages for now.
Update required packages to the latest bugfix versions
=> Solve contradicting dependencies

tests/Integration/IntegrationTest.php
Unless these log entries are expected
=> Enforce Integration tests to be free of warnings or errors

packages/guides-cli/src/Command/Run.php
In our rst-rendering demo the paths where not found the previous way, as we have put `vendor` into `.Build/vendor` via composer
=> Fix paths to template

packages/guides-cli/bin/guides, packages/guides-cli/src/Application.php, packages/guides-symfony/src/DependencyInjection/ContainerFactory.php, packages/guides-symfony/src/DependencyInjection/GuidesExtension.php, packages/guides-symfony/src/DependencyInjection/TestExtension.php, tests/ApplicationTestCase.php, tests/Functional/FunctionalTest.php, tests/Integration/IntegrationBootstrapTest.php, tests/Integration/IntegrationLatexTest.php, tests/Integration/IntegrationPhpDocumentorTest.php, tests/Integration/IntegrationTest.php
This is a split from #333 to try to make smaller steps more quickly :)
Goals of this feature from that PR description:
> * **Centralize the code building the container into a factory.** This makes it easier to change the build process (instead of having to update both the tests and guides "binary"), and allows to add some custom layer for DI extensions.
> * **Give extensions full control** by allowing them to add compiler passes, create configuration trees and load services. This means the container initialization no longer has to register compiler passes that actually belong to a specific package.
=> Introduce ContainerFactory

packages/guides-theme-bootstrap/resources/template/body/menu/mainmenu/menu-level.html.twig, packages/guides-theme-bootstrap/resources/template/body/menu/mainmenu/table-of-content.html.twig, packages/guides-theme-bootstrap/resources/template/body/menu/navbar/menu-level.html.twig, packages/guides-theme-bootstrap/resources/template/body/menu/navbar/table-of-content.html.twig, packages/guides/src/Twig/AssetsExtension.php, tests/Integration/tests-bootstrap/index/expected/index.html, tests/Integration/tests-bootstrap/index/expected/somePage.html
The paths need to have the file ending of the current format, which is not stored in the node. Therefore I introduce a Twig function "renderLink"
=> Fix Paths in Menus

packages/guides/src/DependencyInjection/TestExtension.php, tests/Functional/FunctionalTest.php, tests/Functional/tests/citation/citation.html, tests/Functional/tests/citation/citation.rst
This enables us to run functional tests on some topics that rely on node transformers and passes as long as they don't rely the project structure
=> Run compiler passes in functional tests

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/TextRoleRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/InlineRules/TextRoleRuleTest.php
Added a unittest for the TextRoleRule to cover the use cases including the broken behavior that added the role when a role was defined with a domain.
=> Remove role from raw content with domain

.gitpod.yml, README.rst
GitPot is a fast and easy way to try out the guides without installing them on your local system. You can even use it for development with only using a browser.
Attention: Please squash on merging!
=> Introduce GitPod

Makefile
When running docker with the php image, any command is run as root, unless. It is possible to specify another user to run as with the `--user` option though.
Note that creating the user and group on the docker image does not seem to be required for this to work, so let us just not do it. This spares us from creating a custom entrypoint file.
=> Create files with host user ids

.gitignore, psalm.xml
Before 90fb333, the Psalm cache directory was presumably created in the home directory of the root user.
After that commit, Psalm attempts to create that directory in /, and that fails because of permission issues.
Specifying a cache directory:
- fixes that particular issue;
- more importantly, allows the cache directory to be reused.
Note that `--update-baseline` does not seem to benefit from the cache, so this is really beneficial only when running `vendor/bin/psalm` (no option).
This fixes `make psalm`
=> Specify cache directory for Psalm

packages/guides-cli/src/Command/Run.php, packages/guides/src/Handlers/RenderCommand.php
This adds a progress bar based on how many documents are being processed.
This is not always possible depending on the capabilities of the current `OutputInterface` interface implementation, which it is conditionally created.
For instance, when running tests, you get a `BufferedOutput`, which does not have the section capability.
Closes https://github.com/phpDocumentor/guides/issues/297
=> Add progress bar to the run command

tests/Integration/tests/guilable/expected/index.html, tests/Integration/tests/inline-code/expected/index.html
It was already working, which went unnoticed
=> Unskip Inline tests

packages/guides/resources/template/html/body/menu/content-menu.html.twig, packages/guides/resources/template/html/body/menu/menu.html.twig, packages/guides/resources/template/tex/guides/body/paragraph.tex.twig
Since Twig 2.7, the `spaceless` tag is deprecated in favor of the `spaceless` filter, or the `apply` tag with a `spaceless` argument. I picked the latter so as to still benefit from syntax highlighting.
This is the only deprecation I found while running the test suite with `symfony/phpunit-bridge` locally.
=> Address deprecation of spaceless tag

phpunit.xml.dist
This ensures we cannot have a PHP notice or warning in the test suite. Also, we display details when that happens, for easier debugging.
=> Be stricter about what happens in tests

composer.json, composer.lock, packages/guides-restructured-text/composer.json, packages/guides-restructured-text/src/RestructuredText/Parser/InlineLexer.php, phpstan.neon
This should make it easier to install the project on projects with recent dependencies.
=> Upgrade to doctrine/lexer 3

composer.json, composer.lock, packages/guides-cli/composer.json, packages/guides-graphs/composer.json, packages/guides/composer.json
Here is the output of `composer outdated` after this PR:
```
Direct dependencies required in composer.json:
league/flysystem        1.1.10  3.15.1 Filesystem abstraction: Many filesystems, one API.
league/flysystem-memory 1.0.2   3.15.0 An in-memory adapter for Flysystem.
psr/log                 1.1.4   3.0.0  Common interface for logging libraries
twig/twig               v2.15.5 v3.6.1 Twig, the flexible, fast, and secure template language for PHP
Transitive dependencies not required in composer.json:
amphp/amp               v2.6.2  v3.0.0 A non-blocking concurrency framework for PHP applications.
amphp/byte-stream       v1.8.1  v2.0.1 A stream abstraction to make working with non-blocking I/O simple.
monolog/monolog         2.9.1   3.4.0  Sends your logs to files, sockets, inboxes, …
```
=> Allow Symfony 6

packages/guides-restructured-text/src/RestructuredText/Directives/AbstractAdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/AdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/AdmonitionNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/Nodes/AdmonitionNode.php, packages/guides/resources/template/html/body/admonition.html.twig, tests/Functional/tests/admonitions-contents/admonitions-contents.html, tests/Functional/tests/admonitions-contents/admonitions-contents.rst, tests/Functional/tests/generic-admonition/generic-admonition.html, tests/Integration/tests/class-directive/expected/index.html
In sphinx a general admonition can have a title where the title is the text after the directive declaration. Meanwhile in specialized admonitions such a the note or warning directive the text after the directive declaration, if set, is interpreted as the first paragraph of the content.
=> Support titled and not titled admonitions

composer.json, composer.lock, packages/guides-cli/composer.json, packages/guides-cli/src/Command/Run.php, packages/guides-cli/src/Logger/SpyProcessor.php, packages/guides-cli/tests/unit/Logger/SpyProcessorTest.php
Currently, when all is well, nothing should be logged at all. We can leverage this to use the CLI tool as a linter, and create CI jobs with it.
Here, a new option called `--fail-on-log` is introduced, and it will use a failure exit code as soon as any log is emitted.
This is based on the assumption that the logger is never and will never be called for anything that should not result in a change in the documentation being processed.
=> Fail on log

composer.json, composer.lock, packages/guides-cli/composer.json, packages/guides-cli/src/Logger/SpyProcessor.php, packages/guides/composer.json, tests/Functional/FunctionalTest.php
Output of `composer outdated` after this:
```
Direct dependencies required in composer.json:
league/flysystem        1.1.10  3.15.1 Filesystem abstraction: Many filesystems, one API.
league/flysystem-memory 1.0.2   3.15.0 An in-memory adapter for Flysystem.
twig/twig               v2.15.5 v3.6.1 Twig, the flexible, fast, and secure template language for PHP
Transitive dependencies not required in composer.json:
amphp/amp               v2.6.2  v3.0.0 A non-blocking concurrency framework for PHP applications.
amphp/byte-stream       v1.8.1  v2.0.1 A stream abstraction to make working with non-blocking I/O simple.
psr/http-message        1.1     2.0    Common interface for HTTP messages
```
This should make more realistic to install the guides-cli "the integrated way"
=> Use recent versions of psr/log and Monolog

packages/guides-restructured-text/tests/unit/Parser/Productions/GridTableRuleTest.php
When switching to the logger for error handling in https://github.com/phpDocumentor/guides/pull/472 these tests turned risky as logger->hasError returns a boolean that was not asserted until now
=> Fix risky tests

packages/guides-restructured-text/tests/unit/Parser/Productions/ListRuleTest.php, tests/Functional/tests/list-nested/list-nested.html, tests/Functional/tests/list-nested/list-nested.rst, tests/Functional/tests/list-ordered-nested/list-ordered-nested.html, tests/Functional/tests/list-ordered-nested/list-ordered-nested.rst
I added both unit tests and functional tests. Turns out propper syntax is already working.
resolves https://github.com/phpDocumentor/guides/issues/450
=> Add tests for nested tables

docs/configuration.rst, packages/guides-cli/src/Command/Run.php, packages/guides/resources/config/guides.php, packages/guides/resources/template/html/inline/citation.html.twig, packages/guides/resources/template/html/inline/footnote.html.twig, packages/guides/src/Intersphinx/Inventory.php, packages/guides/src/Intersphinx/InventoryLoader.php, packages/guides/src/Intersphinx/InventoryRepository.php, packages/guides/src/Intersphinx/JsonLoader.php, packages/guides/src/Meta/ExternalTarget.php, packages/guides/src/Meta/InternalTarget.php, packages/guides/src/Meta/Target.php, packages/guides/src/ReferenceResolvers/IntersphinxReferenceResolver.php, packages/guides/src/Settings/ProjectSettings.php, packages/guides/src/Settings/SettingsManager.php, packages/guides/src/Twig/AssetsExtension.php, packages/guides/tests/unit/Intersphinx/InventoryLoaderTest.php, tests/Integration/tests/intersphinx-link/expected/index.html, tests/Integration/tests/intersphinx-link/input/index.rst, tests/Integration/tests/intersphinx-link/input/settings.php
And add functional tests for them
=> Make Intersphinx inventories configurable

packages/guides-restructured-text/resources/config/guides-restructured-text.php, tests/Integration/tests/horizontal-line/expected/index.html, tests/Integration/tests/horizontal-line/input/index.rst
They only worked before the first headline
=> [BUGFIX] make horizontal rules work in document body

packages/guides/resources/config/guides.php, packages/guides/resources/template/html/inline/variable.html.twig, packages/guides/src/NodeRenderers/DefaultNodeRenderer.php, tests/Integration/tests/variables-from-project/expected/index.html, tests/Integration/tests/variables-replace/expected/index.html
Up to now when the value of a node was an array (as for nodes replace and compound) there was an empty string returned in rendering. Added handling of array values (which fixes rendering of the replace directive) and added errrors in case a node that cannot be handled by the defaultnoderenderer is passed to it.
Additionally I removed the superflous new lines in rendering of inline variables
resolves https://github.com/phpDocumentor/guides/issues/509
=> [BUGFIX] Fix the DefaultNodeRenderer for array values

packages/guides/src/Compiler/NodeTransformers/MenuNodeAddEntryTransformer.php, packages/guides/src/Nodes/Menu/MenuEntryNode.php, packages/guides/tests/unit/Compiler/NodeTransformers/MenuNodeAddSubDocumentsTransformerTest.php, tests/Integration/tests/toctree-no-duplicates/expected/index.html, tests/Integration/tests/toctree-no-duplicates/expected/overview.html, tests/Integration/tests/toctree-no-duplicates/input/apple.rst, tests/Integration/tests/toctree-no-duplicates/input/banana.rst, tests/Integration/tests/toctree-no-duplicates/input/cherry.rst, tests/Integration/tests/toctree-no-duplicates/input/index.rst, tests/Integration/tests/toctree-no-duplicates/input/overview.rst
A page that has already been explicitely added to a toctree does not get added by the glob directive once more. As having multiple occurences of the same page within one toctree or menu does not make sense in general, I applied array_unique to the menu_items of one level of the toctree or menu.
@wouterj, @greg0ire is this behaviour also wanted in the doctrine and symfony docs?
=> [BUGFIX] Prevent Duplicates in toctree and menu

packages/guides-restructured-text/src/RestructuredText/Parser/InlineParser.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineMarkupRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/AnnotationRoleRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/AnonymousPhraseRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/AnonymousReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/DefaultTextRoleRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/EmphasisRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/EscapeRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/InlineRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/InternalReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/LiteralRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/NamedPhraseRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/NamedReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/NbspRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/PlainTextRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/ReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/StandaloneEmailRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/StandaloneHyperlinkRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/StrongRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/TextRoleRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/VariableInlineRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/TitleRule.php, packages/guides-restructured-text/tests/unit/Parser/InlineTokenParserTest.php, packages/guides-restructured-text/tests/unit/Parser/Productions/InlineRules/TextRoleRuleTest.php, psalm-baseline.xml
The ParserContext is a Part of the DocumentParserContext, therefore information got lost that will be needed
=> [FEATURE] Make DocumentParserContext Availible in InlineRules

packages/guides-restructured-text/tests/unit/Parser/Productions/InlineRules/TextRoleRuleTest.php
The Namespace was not inline with those of the classes causing unnecessary imports and warnings in the IDE.
=> [BUGFIX] Correct Namespace in Test

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/TextRoleRule.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/LiteralTextRole.php, packages/guides-restructured-text/tests/unit/Parser/Productions/InlineRules/TextRoleRuleTest.php, tests/Functional/tests/code-textrole-no-escape/code-textrole-no-escape.html, tests/Functional/tests/code-textrole-no-escape/code-textrole-no-escape.rst, tests/Functional/tests/escape/escape.html
This is the behaviour of code and literal text roles in Sphinx and reST in general. All three roles now produce the same output
=> [BUGFIX] Content of the code role must not be escaped

docs/extension/_YourExtension.php, docs/extension/_composer.json, docs/extension/_your-extension.php, docs/extension/index.rst, docs/extension/structure.rst, docs/extension/templates.rst
=> [DOCS] Document writing an extension

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/HighlightDirective.php, packages/guides-restructured-text/src/RestructuredText/Parser/DocumentParserContext.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/LiteralBlockRule.php, packages/guides/src/Nodes/CodeNode.php, tests/Integration/tests/code-block-hightlight/expected/index.html, tests/Integration/tests/code-block-hightlight/input/index.rst
to set default languages for code-blocks https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-highlight
depends on #538
=> [FEATURE] introduce highlight directive

packages/guides-restructured-text/src/RestructuredText/Directives/RoleDirective.php, packages/guides-restructured-text/src/RestructuredText/Parser/BlockContext.php, packages/guides-restructured-text/src/RestructuredText/Parser/DocumentParserContext.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/AnnotationRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DefinitionListRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/EnumeratedListRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/FieldList/ProjectFieldListItemRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/FieldList/VersionFieldListItemRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/FieldListRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/GridTableRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/ListRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/ParagraphRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/SimpleTableRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/Table/GridTableBuilder.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/AbstractReferenceTextRole.php, packages/guides/src/Compiler/CompilerContext.php, packages/guides/src/Compiler/NodeTransformers/DocumentEntryRegistrationTransformer.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeAddEntryTransformer.php, packages/guides/src/Compiler/NodeTransformers/VariableInlineNodeTransformer.php, packages/guides/src/NodeRenderers/DefaultNodeRenderer.php, packages/guides/src/ReferenceResolvers/DelegatingReferenceResolver.php, packages/guides/src/Twig/AssetsExtension.php, tests/Functional/FunctionalTest.php, tests/Integration/tests/list-warning/expected/index.html, tests/Integration/tests/list-warning/expected/logs/warning.log, tests/Integration/tests/list-warning/input/index.rst
Add information of the current file and if available line, get Logger Information from the current context
Currently there are messages without any information in the log like:
[2023-08-19T10:29:31.762207+00:00] app.WARNING: List item without content [] []
[2023-08-19T10:29:31.764719+00:00] app.WARNING: List item without content [] []
=> [FEATURE] Make logger messages more verbose

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/Directives/AbstractAdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/AbstractVersionChangeDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/AdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/AttentionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/CautionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ClassDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ContainerDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/DangerDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/DeprecatedDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/DocumentBlockDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ErrorDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/FigureDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/HintDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ImportantDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/NoteDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ReplaceDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/SeeAlsoDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/SidebarDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/SubDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/TipDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/TodoDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/TopicDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/VersionAddedDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/VersionChangedDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/WarningDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/WrapDirective.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/BlockQuoteRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveContentRule.php, tests/Functional/tests/field-list-in-directive/field-list-in-directive.html
This change is breaking for anyone who implemented a SubDirective with a constructor as now the parent constructor has to be called. It also fixes the bug of disappearing field lists in direcitves.
getSubParser is only used in 2 other places that can be dealed with in a follow up such that we can remove the deprecated method all together,
I also removed the subparser in the Blockquotes. So it is only used in the include directive now.
=> !![TASK] Replace the subparser with a starting rule in directives

tests/Functional/tests/links/links.html, tests/Functional/tests/links/links.rst
According to
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup, inline markup must be separated from surrounding text by non-word characters.
Currently, the library does not seem to be checking for the spaces, and it seems that Github's parser has the same behavior: a link between brackets is recognized.
That behavior is nice, and since Github adopted it, it might not be that risky. Let us add a test so that it can be relied on.
=> Endorse divergence from specification for links

packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/GeneralDirectiveNodeRenderer.php, packages/guides-restructured-text/tests/unit/NodeRenderers/Html/GeneralDirectiveNodeRendererTest.php
And handle directives in namespaces as having templates in subdirectories
=> [BUGFIX] Replace special signs in directive template names

packages/guides-restructured-text/src/RestructuredText/Parser/InlineLexer.php, packages/guides-restructured-text/tests/unit/Parser/InlineLexerTest.php, tests/Integration/tests/list-with-code/expected/index.html, tests/Integration/tests/list-with-code/input/index.rst
So it does not catch email like expressions in backticks
=> [BUGFIX] Make Email detection in lexer more strict

packages/guides-cli/bin/guides
If the script is executed from any other locatation but its own project directory we need to search for the guides.xml above the vendor.
=> [FEATURE] Search for configuration in parent of vendor

docs/include.rst.txt, packages/guides-cli/src/Command/Run.php, packages/guides/src/Handlers/RenderCommand.php, packages/guides/src/Renderer/BaseTypeRenderer.php
The progress bar turns the $documents array into an iterator that can only be iterated once and is empty thereafter. We need to use the iterator to render each document so that the progress bar works, but the array to pass to the render context.
=> [BUGFIX] Fix generated menu when progress bar is active

composer.json, composer.lock, packages/guides-markdown/resources/config/guides-markdown.php, tests/ApplicationTestCase.php, tests/Integration/tests/markdown/index-md/expected/index.html, tests/Integration/tests/markdown/index-md/input/guides.xml, tests/Integration/tests/markdown/index-md/input/index.md, tests/Integration/tests/markdown/index-md/input/skip
Install the markdown extension in the composer.json and load it for the integration tests. Introduce a test (still skipped as there are issues to solve)
=> [TASK] Make Markdown availible in integration tests

packages/guides/src/UrlGenerator.php, packages/guides/src/UrlGeneratorInterface.php, packages/guides/tests/unit/UrlGeneratorTest.php
And improve test coverage.
Contains the breaking change of Removing the unused UrlGeneratorInterface::generateUrl as it didnt do anything except leaving each url unchanged and it was not used anymore
=> !!![TASK] Cleanup UrlGeneratorInterface

packages/guides-restructured-text/src/RestructuredText/Directives/FigureDirective.php, packages/guides/src/ParserContext.php, packages/guides/src/RenderContext.php, packages/guides/src/UrlGenerator.php, packages/guides/src/UrlGeneratorInterface.php
It left the input unchanged unless some invalid URL was entered.
In places we seem to have expected it to ltrim slashes which it didnt do.
=> !!![TASK] Remove UrlGeneratorInterface::relativeURL

packages/guides-cli/resources/schema/guides.xsd, packages/guides-cli/src/Command/Run.php, packages/guides/src/DependencyInjection/GuidesExtension.php, packages/guides/src/Settings/ProjectSettings.php, tests/Integration/tests/input-file/expected/README.html, tests/Integration/tests/input-file/input/README.rst, tests/Integration/tests/input-file/input/guides.xml
This can be used to parse READMEs or other standalone reST files. It is also a preparation for rendering specific mark down files in future like a README.md
=> [FEATURE] Add option input-file to render a specific file

packages/guides/resources/template/html/body/image.html.twig, packages/guides/src/Twig/AssetsExtension.php, packages/guides/src/UrlGenerator.php, tests/Functional/tests/image-fullurl/image-fullurl.html, tests/Functional/tests/image-fullurl/image-fullurl.rst
To be able link to external urls we need to check at multiple places how to handle the url.
fixes #621
=> Fix: allow absolute image urls

packages/guides-cli/resources/schema/guides.xsd, packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/MarkupLanguageParser.php, packages/guides-restructured-text/src/RestructuredText/Parser/DocumentParserContextFactory.php, packages/guides/src/DependencyInjection/GuidesExtension.php, packages/guides/src/Settings/ProjectSettings.php, packages/guides/src/Settings/SettingsManager.php, tests/Integration/tests/code/literal-block-default-language-php/expected/index.html, tests/Integration/tests/code/literal-block-default-language-php/input/guides.xml, tests/Integration/tests/code/literal-block-default-language-php/input/index.rst
Besides setting the local language using the `.. highlight::` directive, Sphinx also allows specifying a global default language for literal blocks. We use this in Symfony to mark all literal blocks as "php".
After this PR, you can configure the default language in `guides.xml`:
```xml
<extension class="phpDocumentor\Guides\RestructuredText"
default-code-language="php"
/>
```
=> Allow setting a default language for literal blocks

packages/guides-restructured-text/src/RestructuredText/Parser/DocumentParserContext.php, packages/guides-restructured-text/src/RestructuredText/Parser/InlineLexer.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DocumentRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/AnonymousPhraseRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/AnonymousReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/ReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/LinkRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/LinkRuleTest.php, packages/guides/src/Parser.php, packages/guides/src/ParserContext.php, tests/Functional/tests/anonymous/anonymous.html, tests/Functional/tests/anonymous/anonymous.rst, tests/Functional/tests/image-inline-anonymous/image-inline-anonymous.html, tests/Functional/tests/image-inline-anonymous/image-inline-anonymous.rst
Anonymous links shall not be prefixed by anything. If a word ends with __ (double underscore) no other chars should be prepending other than a white space or a line start.
The links are now part of the document context as they should be reset after every document. This removes the need for extra resets in between.
=> [FIX]: be more strict on anonymous links

.gitignore, Makefile, phpstan.neon, phpunit.xml.dist, psalm.xml
This way all caches can be deleted with deleting .cache, also it is more tidy and we have less files lying around in the main directory
=> [TASK] Move Cache of development tools into /.cache

packages/guides-cli/src/Application.php
Extensions can provide extra commands, in that case we do not want to be a single command application. So do not configure that when multiple commands are set.
=> FEAT: only set default command with signle command app

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/resources/template/html/body/directive/confval.html.twig, packages/guides-restructured-text/src/RestructuredText/DependencyInjection/ReStructuredTextExtension.php, packages/guides-restructured-text/src/RestructuredText/Directives/AbstractAdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/AbstractVersionChangeDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/AdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ClassDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ConfvalDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ContainerDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/DocumentBlockDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/EpigraphDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/FigureDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/GeneralDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/HighlightsDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/OptionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/PullQuoteDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ReplaceDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/SidebarDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/SubDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/TableDirective.php, packages/guides-restructured-text/src/RestructuredText/Nodes/ConfvalNode.php, packages/guides-theme-bootstrap/src/Bootstrap/Directives/TabDirective.php, packages/guides-theme-bootstrap/src/Bootstrap/Directives/TabsDirective.php, tests/Integration/tests/confval/expected/index.html, tests/Integration/tests/confval/expected/objects.inv.json, tests/Integration/tests/confval/input/index.rst
See also https://sphinx-toolbox.readthedocs.io/en/stable/extensions/confval.html
=> [FEATURE] Introduce confval directive

docs/extension/structure.rst, docs/extension/templates.rst, docs/extension/text-roles.rst
Additionally, make two sentences better readable.
=> [BUGFIX] Fix typos in documentation

packages/guides/src/Nodes/ListNode.php, tests/Integration/tests/class/class-in-list/expected/index.html, tests/Integration/tests/class/class-in-list/input/index.rst
@jaapio could you have a look maybe? It seems like even though the  ClassNodeTransformer returns null the node does not get properly removed somewhere in the shadow trees. And I dont really get what the problem is.
=> [TASK] Add failing tests for non-removed class node

packages/guides/resources/config/guides.php, packages/guides/src/DependencyInjection/Compiler/RendererPass.php, packages/guides/src/NodeRenderers/DelegatingNodeRenderer.php, packages/guides/src/RenderContext.php
To make it possible to extend the html rendering with a single document we should allow customization of the html rending stack. The easiest way to do this this to add a new renderer that is reusing the delegating renderer from the html part. By allowing extensions to define their own delegating renderer with a factory set, we can switch towards another stack.
This is a rather complex use case, which we do not support out of the box but needed for typo3.
=> [FIX] support single document rendering

packages/guides-cli/resources/schema/guides.xsd, packages/guides-cli/src/Command/Run.php, packages/guides/resources/config/guides.php, packages/guides/src/DependencyInjection/GuidesExtension.php, packages/guides/src/Interlink/InventoryRepository.php, packages/guides/tests/unit/Interlink/InventoryLoaderTest.php, phpstan-baseline.neon, psalm-baseline.xml, tests/Integration/tests/meta/settings/input/guides.xml, tests/Integration/tests/navigation/intersphinx-link/input/guides.xml, tests/Integration/tests/navigation/intersphinx-numeric/input/guides.xml
By allowing the inventories at the root of our configuration we are more following the standard way of configuring an application in symfony. This will help us to support other configuration formats if we want to.
By moving the initialization of the inventory repository to a parameter extensions can now provide inventories. This could be usefull for non sphinx documentation sets, but still using the interlink functionality. For example when we create a extension that links to the php documentation.
=> [TASK] Make configuration less complex

packages/guides-cli/src/Command/Run.php
Adjusts the meaning of mainly input-file to be clearer.
Adjusts a wrong description of the "output" option.
Enclose arguments with quotes to make it clearer, that these are
the actual values.
Also unifies not having a "." at the end of sentences.
=> [DOCS] Clarify parameter usage for the "guides" binary]

packages/guides/src/Handlers/ParseDirectoryHandler.php
On macOS filesystems, a file-check against "index.rst" using $filesystem->has() would return TRUE, when in fact a file might be stored as "Index.rst". Thus, at this point we fetch the whole directory list and compare the contents with if the INDEX_FILE_NAMES entry matches. This ensures that we get the file with exactly the casing that is returned from the filesystem.
Background:
Given a file called "Index.rst" exists on macOS, executing this script:
```
<?php
echo (file_exists('Index.rst') ? 'Index.rst exists!' : 'Index.rst missing.') . "\n";
echo (file_exists('index.rst') ? 'index.rst exists!' : 'index.rst missing') . "\n";
```
will yield:
```
Index.rst exists!
index.rst exists!
```
but in fact, "index.rst" does not exist. macOS does this by default to prevent case sensitivity issues on …
=> [BUGFIX] Check Document EntryRoot respecting case sensitivity on macOS

packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php, packages/guides/resources/template/html/body/code.html.twig, tests/Integration/tests/class/literalincludeLineNos/expected/index.html, tests/Integration/tests/code/code-block-lineno/expected/index.html, tests/Integration/tests/code/code-block-lineno/input/index.rst
- There was an error triggered by using `lineno-start` option.
- the data-start attribute was output without quotes
- integration tests were missing
resolves #684
=> [BUGFIX] Fix parsing and rendering of code-block with line numbers

packages/guides-cli/bin/guides, packages/guides-cli/resources/config/services.php, packages/guides-cli/src/Application.php, packages/guides-cli/src/Command/WorkingDirectorySwitcher.php, packages/guides-cli/src/DependencyInjection/ApplicationExtension.php
The working dir option allows the user to switch to a different location to execute the application.
=> [FEATURE] allow setting working dir

.github/workflows/integrate.yaml, Makefile, tests/Integration/IntegrationTest.php, tools/xmllint.sh
Linting xml files is not really the responsibility of integration tests.
As a plus using xmllint works on all guides.xml including those in our doc directly and the basic one
=> [TASK] Replace Integration tests with xmllint

packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php, packages/guides-restructured-text/tests/unit/Parser/Productions/DirectiveRuleTest.php, packages/guides/resources/template/html/body/code.html.twig, packages/guides/src/Nodes/CodeNode.php, tests/Integration/tests/code/code-block-emphasize/expected/index.html, tests/Integration/tests/code/code-block-emphasize/input/index.rst
resolves https://github.com/phpDocumentor/guides/issues/688
=> [FEATURE] Support emphasize-lines in code-block directive

packages/guides-cli/src/Command/Run.php, packages/guides/src/Handlers/RenderCommand.php, packages/guides/src/RenderContext.php, packages/guides/src/Renderer/BaseTypeRenderer.php, packages/guides/src/Renderer/DocumentListIterator.php, packages/guides/src/Renderer/DocumentTreeIterator.php, packages/guides/src/Renderer/LatexRenderer.php, packages/guides/tests/unit/Renderer/DocumentListIteratorTest.php, packages/guides/tests/unit/Renderer/DocumentTreeIteratorTest.php, packages/guides/tests/unit/Renderer/IteratorTestCase.php, phpcs.xml.dist, phpstan-baseline.neon, psalm-baseline.xml
The newly added iterators do iterate the toc tree to find the order of rendering of documents. This is required to have single page outputs in the correct order. The downside of this new approach is that only documents that are in a toc-tree are rendered.
=> !!![FEATURE] add document iterator

packages/guides/src/ReferenceResolvers/AnchorReferenceResolver.php, packages/guides/src/ReferenceResolvers/DocReferenceResolver.php, tests/Integration/tests/navigation/interlink-to-index/expected/Index.html, tests/Integration/tests/navigation/interlink-to-index/input/Index.rst, tests/Integration/tests/navigation/interlink-to-index/input/guides.xml
DocumentReferenceResolver at times tried to resolve intersphinx links leading to strange unexpected behaviour.
=> [BUGFIX] Do not use local resolvers for interlinks

packages/guides/composer.json
DependencyInjection/TestExtension.php uses the symfony/clock package, but it is not defined as a dependency.
=> [BUGFIX] Add missing symfony/clock dependency

packages/guides-restructured-text/src/RestructuredText/TextRoles/AbstractReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/DocReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/GenericReferenceTextRole.php, packages/guides/src/Interlink/InventoryRepository.php, packages/guides/tests/unit/Interlink/InventoryLoaderTest.php, tests/Integration/tests/interlink/interlink-to-doc-in-path/expected/Index.html, tests/Integration/tests/interlink/interlink-to-doc-in-path/input/Index.rst, tests/Integration/tests/interlink/interlink-to-doc-in-path/input/guides.xml
So does Sphinx and we use it frequently in TYPO3. Additionally Better document the regex and use a central one instead of copying it twice
=> [BUGFIX] Allow underscore and minus in interlink names

packages/guides/src/RenderContext.php, packages/guides/src/Renderer/InterlinkObjectsRenderer.php, packages/guides/src/Renderer/UrlGenerator/RelativeUrlGenerator.php, packages/guides/tests/unit/Renderer/UrlGenerator/RelativeUrlGeneratorTest.php
This enables single file renderers like singlehtml to also calculate relative paths.
Needed for https://github.com/TYPO3-Documentation/render-guides/pull/130
=> [BUGFIX] Use output filename with path in relative path calculations

.github/workflows/integrate.yaml
The ci script does now automatically detect the supported phpversions from the composer.json and builds against those versions
=> [CI] start building on php 8.3

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/FieldListRule.php, tests/Integration/tests/lists/field-list-empty-lines/expected/index.html, tests/Integration/tests/lists/field-list-empty-lines/input/index.rst
They are also allowed in Sphinx and we frequently have them in TYPO3.
=> [BUGFIX] Allow empty lines between field list items

packages/guides-restructured-text/src/RestructuredText/Parser/LinesIterator.php, tests/Integration/tests/code/code-block-with-underscore/expected/index.html, tests/Integration/tests/code/code-block-with-underscore/input/index.rst
In some legacy rst files in TYPO3 this is still being used. Currently it leads to a large amount of warnings
=> [BUGFIX] Allow tabs in line indentations

packages/guides-restructured-text/src/RestructuredText/Parser/InlineLexer.php, packages/guides-restructured-text/tests/unit/Parser/InlineLexerTest.php, tests/Functional/tests/guilabel/guilabel.html, tests/Functional/tests/links/links.html
We had strange bugs where String like "Icon::SIZE_*" where interpreted as named refernce without having any reason to be so.
This was due to two problems:
The catchable pattern for external hyperlinks was also catching this pattern, so it was treated as a complete token.
The interpretation of the tokens in InlineLexer::gettype interpreted PART of the resulting string as named reference and marked the complete token as named_reference
I changed the catchable pattern to not catch these tokens. I am still not happy with the regex here but cannot dive into it.
I made sure that in InlineLexer::gettype() we test against the complete string as the $value passed to it is already tokenized.
This also changed the output from two functional tests that stemmed form strings with a double point beeing …
=> [BUGFIX] Prevent false positives in Lexer

tools/xmllint.sh
Just had an issue where he found some files in the .git area, however those must not be checked
=> [BUGFIX] Ignore .git and .cache directories on xml lint

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/VariableInlineRule.php, tests/Integration/tests/text-with-pipe/expected/index.html, tests/Integration/tests/text-with-pipe/input/index.rst
Other variable names are not possible and this prevents so many false positives in texts with pipes.
=> [BUGFIX] Limit inline variables to Alphanumeric + Underscore

composer.lock, packages/guides-restructured-text/src/RestructuredText/Directives/CsvTableDirective.php
That version adds more insight on what is returned by `League\Csv::getRecords()`, which is now documented as an `Iterator<array<mixed>>`. Since we are using strict types, we are already assuming that mixed will in fact always be a string or null. Let's make the assumption clear to static analysis tools.
=> Upgrade to latest league/csv

packages/guides-restructured-text/src/RestructuredText/Parser/EmbeddedUriParser.php, packages/guides-restructured-text/src/RestructuredText/Parser/InlineLexer.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/AnonymousPhraseRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/NamedPhraseRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/ReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/AbstractReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/DocReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/GenericReferenceTextRole.php, packages/guides-restructured-text/tests/unit/Parser/InlineTokenParserTest.php, packages/guides-restructured-text/tests/unit/TextRoles/DocReferenceTextRoleTest.php, packages/guides-restructured-text/tests/unit/TextRoles/ReferenceTextRoleTest.php, tests/Functional/tests/links/links.html, tests/Functional/tests/links/links.rst
These characters are valid and only the last `<...>` must be treated as the embedded URL.
This PR removes using the inline lexer inside references, reSt doesn't allow nested inline nodes and the only thing required is getting the embedded URL (if there is any). This reduces a lot of complexity
=> Fix using < or > in a reference name

packages/guides-cli/bin/guides
Imagine this file structure:
```
project/
+ docs/
+ vendor/
|   + phpdocumentor/
|       + guides-cli/
+ guides.xml
```
Running the CLI from the project root would result in `guides.xml` to be loaded twice. This PR fixes it, and also improves the verbose output by resolving all the `/../` parts in the filepath.
=> Do not include config files twice

packages/guides-restructured-text/src/RestructuredText/Directives/SidebarDirective.php, packages/guides-restructured-text/src/RestructuredText/Nodes/SidebarNode.php, packages/guides/resources/template/html/structure/sidebar.html.twig, tests/Functional/tests/sidebar/sidebar.html, tests/Functional/tests/sidebar/sidebar.rst
Sidebar titles are allowed to contain inline markup.
This is a small BC break, as we change the property of the section node.
=> Render inline nodes in sidebar title

.github/workflows/documentation.yml, docs/rst-reference/text-roles.rst
This project is a rare exception of a project that actually needs to build its docs when the code changes, because it is using itself to build those docs.
=> Build docs when the source code change

packages/guides/resources/template/html/structure/section.html.twig, packages/guides/resources/template/tex/structure/section.tex.twig, packages/guides/src/Nodes/SectionNode.php, packages/guides/tests/unit/Compiler/NodeTransformers/MoveAnchorTransformerTest.php, packages/guides/tests/unit/Compiler/ShadowTree/TreeNodeTest.php, tests/Integration/tests/anchor/anchor-ref-title-equals-title/expected/overview.html, tests/Integration/tests/anchor/anchor-title-overriden-by-ref-title/expected/index.html, tests/Integration/tests/anchor/anchor-to-title/expected/index.html, tests/Integration/tests/anchor/anchor-whitespace/expected/index.html, tests/Integration/tests/hyperlink-to-page/expected/subpages/index.html, tests/Integration/tests/navigation/reference-not-found/expected/index.html, tests/Integration/tests/navigation/references/expected/index.html, tests/Integration/tests/references/reference-level-3-relative/expected/level-1-1/level-2-1/subpage1.html, tests/Integration/tests/references/reference-level-3-relative/expected/level-1-2/subpage2.html, tests/Integration/tests/references/reference-level-3/expected/level-1-1/level-2-1/subpage1.html, tests/Integration/tests/references/reference-level-3/expected/level-1-2/subpage2.html
Hyperlink targets (or Anchor nodes) of a section are currently parsed as child nodes. This is alright, but causes a rendering issue as the anchors are placed below the title node. This means that referencing such anchors scrolls the section title outside of the view.
I don't like my solution in this PR, but it at least fixes the bug by placing the anchor nodes before the title node (which is how Sphinx does it). If anyone has a better suggestion, please tell me :)
| *Before* | *After*
| --- | ---
| ![image](https://github.com/phpDocumentor/guides/assets/749025/d6b333af-2de5-46ef-b546-0650a4eff464) | ![image](https://github.com/phpDocumentor/guides/assets/749025/e9a4e76a-a63c-4c26-980f-6de1ad3aa2c3)
=> Move section anchors before the section title

tests/Integration/tests/references/reference-with-escape/expected/index.html, tests/Integration/tests/references/reference-with-escape/input/index.rst, tests/Integration/tests/references/reference-with-escape/input/skip
References work correctly, but somehow we rendering the escape slashes in named phrases.
```
--- Expected
+++ Actual
@@ @@
'<div class="section" id="the-head">\n
<h1>the &lt;head&gt;</h1>\n
<a id="anchor"></a>\n
-<p>See also <a href="/index.html#anchor">the &lt;head&gt; of this file</a> or <a href="/index.html#the-head">the &lt;head&gt;</a>.</p>\n
+<p>See also <a href="/index.html#anchor">the &lt;head&gt; of this file</a> or <a href="/index.html#the-head">the \&lt;head\&gt;</a>.</p>\n
</div>'
```
=> Fix usage of ref text role

packages/guides/src/RenderContext.php
In standard renderings output and input filenames with their paths are the same except for the file ending. However, in project based rendering nodes the currentFileName in the rendering context is null, leading to an error.
In these cases we add the outputfile path manually to the render context.
The relative urls must now be calculated relative to the output path, not the input path.
=> [BUGFIX] Use output file path for relative url calculations

packages/guides/src/RenderContext.php
Right now I have to try querrying getCurrentFileName and then catch the Exception. I would like to know if there is one
=> [TASK] add hasCurrentFileName to RenderContext

packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/AdmonitionNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/CollectionNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/ContainerNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/GeneralDirectiveNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/SidebarNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/TopicNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/LaTeX/GeneralDirectiveNodeRenderer.php, packages/guides/src/NodeRenderers/DefaultNodeRenderer.php, packages/guides/src/NodeRenderers/DelegatingNodeRenderer.php, packages/guides/src/NodeRenderers/Html/BreadCrumbNodeRenderer.php, packages/guides/src/NodeRenderers/Html/DocumentNodeRenderer.php, packages/guides/src/NodeRenderers/Html/MenuEntryRenderer.php, packages/guides/src/NodeRenderers/Html/MenuNodeRenderer.php, packages/guides/src/NodeRenderers/Html/TableNodeRenderer.php, packages/guides/src/NodeRenderers/Html/TemplatedNodeRenderer.php, packages/guides/src/NodeRenderers/InMemoryNodeRendererFactory.php, packages/guides/src/NodeRenderers/LaTeX/TableNodeRenderer.php, packages/guides/src/NodeRenderers/LaTeX/TitleNodeRenderer.php, packages/guides/src/NodeRenderers/LaTeX/TocNodeRenderer.php, packages/guides/src/NodeRenderers/NodeRenderer.php, packages/guides/src/NodeRenderers/OutputAwareDelegatingNodeRenderer.php, packages/guides/src/NodeRenderers/PreRenderers/PreRenderer.php, packages/guides/src/NodeRenderers/TemplateNodeRenderer.php
By caching which node renderer can be used for which node, we can avoid a lot of foreach loops.
From a quick local test (with pcov enabled), this improved run time by 50%. Blackfire diff: https://blackfire.io/profiles/compare/9aa42af9-7692-418c-9d34-f7e010a22f8f/graph
We can optionally do this in a non-BC breaking way by introducing a new cacheable interface with a `supportsFqcn()` method (similar to Symfony's [voter caching](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Security/Core/Authorization/Voter/CacheableVoterInterface.php)). However, I can find no node renderer in guides and Symfony that does something other than `instanceof`. So I would favor simplicity for the years to come over this BC break.
But I'm happy to discuss rewriting this to a smooth upgrade path …
=> Cache matching node renderers

packages/guides/src/Renderer/DocumentListIterator.php, packages/guides/tests/unit/Renderer/DocumentListIteratorTest.php, phpstan-baseline.neon
Changed the logic of moving in the document iterator, this removes some complexity to make the iterator easier to understand.
Fixes #757
=> [FIX] issue with document iterator

tests/Integration/tests/toctree/toctree-maxdepth/expected/index.html, tests/Integration/tests/toctree/toctree-maxdepth/input/index.rst, tests/Integration/tests/toctree/toctree-maxdepth/input/page1.rst, tests/Integration/tests/toctree/toctree-maxdepth/input/skip, tests/Integration/tests/toctree/toctree-maxdepth/input/subpage1/page1.rst, tests/Integration/tests/toctree/toctree-maxdepth/input/subpage1/page2.rst, tests/Integration/tests/toctree/toctree-maxdepth/input/subpage2/page1.rst
Unfortunately, it seems like we do not yet properly support maxdepth on toctrees. Almost all tests were using it in combination with `titlesonly`, but it seems completely broken without this option. In the Symfony docs, we only have toctrees with `:maxdepth: 1` without `:titlesonly:`, so I'm afraid guides must support the option properly for us to move to guides.
I've added a test case for this, the expected file is verified with Sphinx' behavior. Currently, guides renders 4 times the same toctree. The maxdepth option seems not to be taken into account for how many subtitles it must render, and the documents in sub-toctrees are not in the list (the latter is not something we rely on in Symfony docs btw).
<details><summary>Current HTML output</summary>
```html
<div class="toc">
<ul …
```
=> Add tests for maxdepth option on toctree without titlesonly

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/Parser/Interlink/DefaultInterlinkParser.php, packages/guides-restructured-text/src/RestructuredText/Parser/Interlink/InterlinkData.php, packages/guides-restructured-text/src/RestructuredText/Parser/Interlink/InterlinkParser.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/AbstractReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/DocReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/GenericReferenceTextRole.php, packages/guides-restructured-text/tests/unit/Parser/InlineTokenParserTest.php, packages/guides-restructured-text/tests/unit/TextRoles/DocReferenceTextRoleTest.php
In TYPO3 we want to allow additonal special signs, so that interlinks to composer names can be made.
Additionally, this also removed duplicate code
=> [FEATURE] Introduce exchangeable InterlinkParser

packages/guides-cli/src/Command/Run.php, packages/guides/src/Event/PostCollectFilesForParsingEvent.php, packages/guides/src/Event/PostRenderDocument.php, packages/guides/src/Event/PreRenderProcess.php, packages/guides/src/Files.php, packages/guides/src/Handlers/ParseDirectoryHandler.php, phpstan-baseline.neon
* Display a progress bar during parsing
* Display one progress bar per renderer
* Introduce an event once the files have been collected for parsing
This gives me progress bars like this after rendering:
Parsing: 16/16 [============================] 100% Parsed 16 files in 0.98 seconds
Rendering: 16/16 [============================] 100% Output format html: Rendered 16 documents in 0.71 seconds
Rendering: 16/16 [============================] 100% Output format interlink: Rendered 16 documents in 0.00 seconds
During rendering and during parsing the currently handled file is displayed.
=> [TASK] Improve progress bar

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/AnonymousPhraseRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/NamedPhraseRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/ReferenceRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/References/EmbeddedReferenceParser.php, packages/guides-restructured-text/src/RestructuredText/Parser/References/ReferenceData.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/AbstractReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/Toc/ToctreeBuilder.php
Renamed the trait EmbeddedUriParser to EmbeddedReferenceParser as it can be used for all kind of references including internals.
Let the EmbeddedReferenceParser return a DTO.
Unify the naming an usage of URL parts.
=> !!![TASK] Improve Reference parsing

packages/guides-code/resources/template/html/body/code/highlighted-code.html.twig, packages/guides-code/src/Code/DependencyInjection/CodeExtension.php, packages/guides-code/src/Code/Highlighter/HighlightPhpHighlighter.php, packages/guides-code/src/Code/Highlighter/Highlighter.php, packages/guides-code/src/Code/Twig/CodeExtension.php, packages/guides-code/tests/unit/Highlighter/HighlightPhpHighlighterTest.php, packages/guides/resources/template/html/body/code.html.twig, packages/guides/resources/template/html/body/code/highlighted-code.html.twig, packages/guides/src/Twig/TwigTemplateRenderer.php
* Add default templates
* Use it for our own documentation
* Treat rest and unknown language as "text"
* Use warnings for unknown languages and supply debugging information
* As i also want to use the debugInformation for our third-party highlighter, I introduced a new global into twig which only contains the array. This way third party packages do not have to know about the RenderContext.
=> [FEATURE] Make code extension work out-of-the box

composer.json, docs/index.rst, packages/guides-cli/src/Command/Run.php, packages/guides/resources/config/guides.php, packages/guides/src/Event/PostProjectNodeCreated.php, packages/guides/src/EventListener/LoadSettingsFromComposer.php, packages/guides/src/Nodes/ProjectNode.php, packages/guides/src/Settings/ComposerSettingsLoader.php
Load data like description, support links, composer name etc from the composer.json if one is found.
=> [FEATURE] Load data from composer.json if present

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/DependencyInjection/ReStructuredTextExtension.php, packages/guides-restructured-text/src/RestructuredText/Directives/ConfigurationBlockDirective.php, packages/guides/resources/template/html/body/configuration-block.html.twig, packages/guides/resources/template/html/template.php, packages/guides/src/Nodes/Configuration/ConfigurationBlockNode.php, packages/guides/src/Nodes/Configuration/ConfigurationTab.php, phpstan-baseline.neon, psalm-baseline.xml, tests/Integration/tests/directives/directive-configuration-block/expected/index.html, tests/Integration/tests/directives/directive-configuration-block/input/guides.xml, tests/Integration/tests/directives/directive-configuration-block/input/index.rst
Add the implementation of the configuration block directive. To make the implemtation more generic a configuration option is introduced. This will allow the users to configure their own labels.
=> [FEATURE] add configuration block directive

packages/guides/resources/template/html/body/menu/menu-item.html.twig, tests/Integration/tests/navigation/menu-relative/input/level-1-1/index.rst
Menu items should be plain text, do not render the nodes of the title. Just get the plaintext string.
fixes #814
=> [FIX] Do not use html elements in menu items

packages/guides-theme-bootstrap/resources/template/body/menu/mainmenu/menu.html.twig, packages/guides/src/Compiler/Passes/GlobalMenuPass.php, tests/Integration/tests-full/bootstrap/bootstrap-default-menu-several/expected/anotherPage.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu-several/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu-several/expected/somePage.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu-several/expected/subpages/index.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu-several/expected/subpages/subpage1.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu-several/expected/subpages/subpage2.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu-several/expected/yetAnotherPage.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu/expected/anotherPage.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-default-menu/expected/somePage.html, tests/Integration/tests-full/bootstrap/bootstrap-default-subpages-max-1/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-default-subpages-max-2/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-default-subpages-max-3/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-default-subpages/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-default-subpages/input/index.rst, tests/Integration/tests-full/bootstrap/bootstrap-index/expected/anotherPage.html, tests/Integration/tests-full/bootstrap/bootstrap-index/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-index/expected/somePage.html, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-linktargets/expected/index.html
Resolves #803
@wouterj does this resolve your issue?
=> [BUGFIX] Correct Menu levels in global menu tree

packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php, packages/guides-restructured-text/src/RestructuredText/Parser/LinesIterator.php, tests/Integration/tests/code/code-block-empty/expected/index.html, tests/Integration/tests/code/code-block-empty/expected/logs/warning.log, tests/Integration/tests/code/code-block-empty/input/index.rst, tests/Integration/tests/directives/directive-configuration-block/expected/index.html
=> [TASK] Warn when code-block has no content

packages/guides-cli/bin/guides
Running the tool without creating a guides.xml is a valid scenario, and should be supported. This means realpath() may return false, which is not a valid input for is_file().
Fixes #824
=> Resolve path after checking it leads to an existing file

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveRule.php, tests/Integration/tests/graphs/plantuml-external/expected/Plantuml/index.html, tests/Integration/tests/graphs/plantuml-external/expected/index.html, tests/Integration/tests/toctree/toctree-maxdepth/expected/index.html
This enables themes to define additional options that can then be used in the theme, for example additional information for code-nodes.
This also fixes an undetected bug in graphs where the width option was swalloed
=> [TASK] Forward directive options to node

packages/guides/src/DependencyInjection/GuidesExtension.php, tests/Integration/tests/meta/version-from-guides-xml/input/skip
Fixes #829 
Don't ask me how/why this works, I just bluntly copied it from @jaapio's work on phpDocumentor's config (https://github.com/phpDocumentor/phpDocumentor/commit/991adcf381140a5900566e2bdb57cef3f8db343c).
=> Revert phpize for versions, never treat them like numbers

packages/guides-cli/src/Command/Run.php
`getAbsolutePath()` was introduced in #284, but it is unclear to me why. Removing it seems to fix UX inconsistencies without introducing other issues.
It causes non-existent relative paths to be treated differently than non-existent absolute paths: using the former crashes the program, while using the latter results in directories being created at the provided paths.
Closes #825
=> Work with relative paths

packages/guides/src/ReferenceResolvers/AnchorReferenceResolver.php, tests/Integration/tests/interlink/interlink-ref-inventory-unknown/expected/Index.html, tests/Integration/tests/interlink/interlink-ref-inventory-unknown/expected/logs/warning.log, tests/Integration/tests/interlink/interlink-ref-inventory-unknown/input/Index.rst, tests/Integration/tests/interlink/interlink-ref-inventory-unknown/input/guides.xml
Otherwise, references to an unknown interlink reference get rendered as if they are an internal anchor link.
Resolves https://github.com/phpDocumentor/guides/issues/837
=> [BUGFIX] Anchor References may not have an interlink part

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/ContainerNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/LineBlockRule.php, tests/Integration/tests/body-elements/line-blocks/expected/index.html, tests/Integration/tests/body-elements/line-blocks/input/index.rst, tests/Integration/tests/body-elements/line-blocks/input/skip
Line blocks are just lines in a div that can be nested using indentation. Every line must start with an | and a block ends when an empty line is detected.
I implemented this using ContainerNodes because it's an rst only type, and it has no other behavior rather than just some custom styling.
=> [FEATURE] Add line block support

packages/guides-restructured-text/src/RestructuredText/Parser/References/EmbeddedReferenceParser.php, tests/Integration/tests/references/reference-without-space/expected/index.html, tests/Integration/tests/references/reference-without-space/input/index.rst
While reST expects a whitespace here, Sphinx allows to omit the whitespace and still interprets them correctly.
=> [TASK] Allow to omit whitespace before reference target

packages/guides/composer.json, packages/guides/src/Renderer/InterlinkObjectsRenderer.php
for improved interoperability when interlinking from a Sphinx document to a guides document
See also: https://sphobjinv.readthedocs.io/en/stable/syntax.html
=> [FEATURE] Provide Sphinx inventory version 2

packages/guides/src/ReferenceResolvers/Interlink/DefaultInventoryLoader.php, packages/guides/tests/unit/Interlink/InventoryLoaderTest.php, packages/guides/tests/unit/Interlink/fixtures/null-in-objects.inv.json
Handle null values as not set, ignore inventory entries that have non-scalar values or null in the URI.
Until now those were causing type errors
=> [BUGFIX] Handle "dirty" objects.inv.json data

composer.json, composer.lock, packages/guides-restructured-text/src/RestructuredText/Directives/SectionauthorDirective.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/ListRule.php, packages/guides/src/UriFactory.php, phpstan.neon
A https://regex101.com link makes regexes easier to understand, test and change.
We have the same tests in the render-guides at typo3
=> [TASK] Enforce REGEX Documentation

packages/guides/src/FileCollector.php, tests/Integration/tests/numeral-rst/expected/index.html, tests/Integration/tests/numeral-rst/expected/objects.inv.json, tests/Integration/tests/numeral-rst/input/404.rst, tests/Integration/tests/numeral-rst/input/index.rst
Currently pages such as 404.rst cause type errors and fail the application.
=> [BUGFIX] Treat numeral filenames as string

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/CommentRule.php, tests/Functional/tests/comment-empty/comment-empty.html, tests/Integration/tests/class/class-directive/expected/index.html, tests/Integration/tests/class/class-directive/input/index.rst, tests/Integration/tests/comments/comment-multiline/expected/index.html, tests/Integration/tests/comments/comment-multiline/input/index.rst, tests/Integration/tests/comments/comment-nested/expected/index.html, tests/Integration/tests/comments/comment-nested/input/index.rst
See https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#comments
There were some old functional tests stating that a block citation after and empty comment is displayed, this is wrong however.
=> [BUGFIX] Multiline comments may contain empty lines

packages/guides-restructured-text/src/RestructuredText/Directives/ConfigurationBlockDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/CsvTableDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/TableDirective.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/GeneralDirectiveNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/LaTeX/GeneralDirectiveNodeRenderer.php, packages/guides-theme-bootstrap/src/Bootstrap/Directives/TabsDirective.php, tests/Integration/tests/directives/directive-unkown/expected/logs/warning.log
Extended warning information from the context was missing in some warnings. This makes debugging harder.
=> [TASK] Improve Warnings

packages/guides-restructured-text/src/RestructuredText/TextRoles/AbbreviationTextRole.php, tests/Functional/tests/text-roles/text-roles.html, tests/Functional/tests/text-roles/text-roles.rst
In Sphinx it is an alias for :abbreviation:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-abbr
resolves #899
=> [BUGFIX] Support :abbr: textrole

packages/guides-restructured-text/src/RestructuredText/Directives/OptionMapper/DefaultCodeNodeOptionMapper.php, tests/Integration/tests/code/code-block-emphasize/expected/index.html, tests/Integration/tests/code/code-block-emphasize/input/index.rst
Sphinx also allows these
Improve error message
=> [BUGFIX] Allow emphasize-lines with open end

packages/guides/resources/config/guides.php, packages/guides/src/RenderContext.php, packages/guides/src/Twig/AssetsExtension.php, packages/guides/src/Twig/GlobalMenuExtension.php
By introducing a cache array for menus we do improve the speed when menus are multiple times rendered.
=> [TASK] Improve menu rendering speed

packages/guides-restructured-text/src/RestructuredText/Directives/ImageDirective.php, packages/guides/resources/config/guides.php, packages/guides/resources/template/html/body/image.html.twig, packages/guides/src/Nodes/ImageNode.php, packages/guides/src/ReferenceResolvers/ImageReferenceResolverPreRender.php, tests/Integration/tests/images/image-target/expected/images/hero2-illustration.svg, tests/Integration/tests/images/image-target/expected/index.html, tests/Integration/tests/images/image-target/input/guides.xml, tests/Integration/tests/images/image-target/input/images/hero2-illustration.svg, tests/Integration/tests/images/image-target/input/index.rst, tests/Integration/tests/images/image-target/input/subfolder/subpage.rst
resolves https://github.com/phpDocumentor/guides/issues/911
=> [FEATURE] Support directive image with target

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/Directives/ListTableDirective.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/ListRule.php, packages/guides/src/Compiler/NodeTransformers/ListNodeTransformer.php, phpstan-baseline.neon, tests/Integration/tests/lists/list-warning/expected/logs/warning.log, tests/Integration/tests/tables/list-table-directive/expected/index.html, tests/Integration/tests/tables/list-table-directive/input/index.rst
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html
resolves #890
@jaapio can we still backport features?
=> [FEATURE] Support list-table directive

packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/ExternalMenuEntryNodeTransformer.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/MenuEntryManagement.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/SubInternalMenuEntryNodeTransformer.php, packages/guides/src/Compiler/Passes/GlobalMenuPass.php, packages/guides/src/Nodes/DocumentTree/DocumentEntryNode.php, packages/guides/src/Nodes/DocumentTree/EntryNode.php, packages/guides/src/Nodes/DocumentTree/ExternalEntryNode.php, packages/guides/src/Nodes/DocumentTree/SectionEntryNode.php, packages/guides/src/Nodes/Menu/InternalMenuEntryNode.php, packages/guides/src/Renderer/DocumentTreeIterator.php, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-on-subpage/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-on-subpage/input/guides.xml, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-on-subpage/input/index.rst, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-on-subpage/input/page1.rst
Sphinx handels it also that way
=> [BUGFIX] Display external pages on all levels of the main menu

packages/guides-restructured-text/resources/template/html/body/directive/glossary.html.twig, tests/Integration/tests/directives/directive-glossary/expected/index.html, tests/Integration/tests/directives/directive-glossary/input/index.rst, tests/Integration/tests/tables/list-table-directive/expected/index.html
Support glossary directive containing a definition list. Multiple terms, groups and :sorted: flag are not yet supported
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-glossary
resolves: #929
=> [FEATURE] Support basic glossary directive

packages/guides-cli/src/Command/Run.php, packages/guides/src/FileCollector.php, packages/guides/src/Handlers/ParseDirectoryCommand.php, packages/guides/src/Handlers/ParseDirectoryHandler.php
E.g. in the Symfony docs, we must exclude the `_build` directory from the source directory (the project's root) to not get rst files from dependencies parsed. I can imagine excluding `vendor/` makes sense for more repositories.
EDIT: Hah, I didn't know I was submitting this PR right when 1.0.0 was released. Fortunately, the changes in this PR are backwards-compatible so it's completely fine for a 1.1 release.
=> Allow excluding paths from the source directory

packages/guides-cli/bin/guides
This adresses:
* OutputInterface namespace import is unused
* realpath() may fail, needs gating to satisfy phpstan even though it's unlikely that is_file() returns true, but realpath() doesn't.
* Currently only `--config` and not `-c` is parsed, same with `--working-dir` (`-w`)
* Note: A phpstan error remains due to `getcwd()` maybe returning false and I didn't want to obfuscate this statement with if-condititions; if you have suggestions to improve the type juggling here, tell me.
=> [BUGFIX] Fix non-working short-options for "config" and "working-dir"

packages/guides-restructured-text/resources/template/html/body/directive/confval.html.twig, packages/guides-restructured-text/src/RestructuredText/Directives/ConfvalDirective.php, packages/guides-restructured-text/src/RestructuredText/Nodes/ConfvalNode.php, packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php, packages/guides/src/Nodes/OptionalLinkTargetsNode.php, tests/Integration/tests/confval/confval-noindex/expected/another.html, tests/Integration/tests/confval/confval-noindex/expected/index.html, tests/Integration/tests/confval/confval-noindex/expected/objects.inv.json, tests/Integration/tests/confval/confval-noindex/input/another.rst, tests/Integration/tests/confval/confval-noindex/input/index.rst
https://sphinx-toolbox.readthedocs.io/en/stable/extensions/confval.html#directive-option-confval-noindex
=> [FEATURE] Introduce noindex option for confvals

tests/Integration/tests/graphs/plantuml-server-error/expected/index.html, tests/Integration/tests/graphs/plantuml-server-error/expected/logs/warning.log, tests/Integration/tests/graphs/plantuml-server-error/input/Plantuml/something.plantuml, tests/Integration/tests/graphs/plantuml-server-error/input/guides.xml, tests/Integration/tests/graphs/plantuml-server-error/input/index.rst
=> [TASK] Add test to prove proper error handling for plantuml

packages/guides-theme-bootstrap/resources/config/guides-theme-bootstrap.php, packages/guides-theme-bootstrap/resources/template/body/directive/accordion.html.twig, packages/guides-theme-bootstrap/src/Bootstrap/Directives/AccordionDirective.php, packages/guides-theme-bootstrap/src/Bootstrap/Directives/AccordionItemDirective.php, packages/guides-theme-bootstrap/src/Bootstrap/Nodes/AccordionItemNode.php, packages/guides-theme-bootstrap/src/Bootstrap/Nodes/AccordionNode.php, packages/guides/src/Nodes/TitleNode.php, tests/Integration/tests/bootstrap/bootstrap-accordion/expected/index.html, tests/Integration/tests/bootstrap/bootstrap-accordion/input/guides.xml, tests/Integration/tests/bootstrap/bootstrap-accordion/input/index.rst
(cherry picked from commit 61a414c0113fd7eea114642f177ac48546cdbad7)
=> [BACKPORT][FEATURE] Introduce directives for bootstrap accordions

packages/guides/src/RenderContext.php
Currently to get the current document you have to do
$document = $renderContext->getDocumentNodeForEntry($renderContext->getCurrentDocumentEntry());
even though the document is saved in a variable
=> [TASK] Add getter for Documents to RenderContext

packages/guides-restructured-text/src/RestructuredText/Parser/InlineLexer.php, packages/guides-restructured-text/tests/unit/Parser/InlineLexerTest.php
I did not found any specification where an URL can contain parenthesis in the url, nor we do have a test that fails on this case. If we need it anyway we can introduce it later on. But for now this fixes a bug where the fetch of a url is way to gredy.
=> Fix invalid url parsing

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/Table/GridTableBuilder.php
This PR is  a preparation to make #955 easier to solve. It should not change functionality
=> [TASK] Refactor GridTableBuilder

packages/guides/src/DependencyInjection/GuidesExtension.php, tests/Integration/tests/configuration/config-project/expected/index.html, tests/Integration/tests/configuration/config-project/input/guides.xml, tests/Integration/tests/meta/version-from-guides-xml/input/guides.xml
symfony is trying to normalize the xml input using
some logic. However in our case we want to fetch the raw value for version. But this is not possible. therefor an escape system is added by adding `'`.
fixes #1057
=> [BUGFIX] do not parse version config node

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/Table/GridTableBuilder.php, packages/guides-restructured-text/tests/unit/Parser/Productions/GridTableRuleTest.php, packages/guides/src/Nodes/Table/TableColumn.php, packages/guides/src/Nodes/Table/TableRow.php, tests/Integration/tests/tables/grid-table-with-list/expected/index.html
Table cells may contain multiple lines as we did trim the cell content before the table parsing was completed we did mis empty lines. As empty lines where missing we did break the parsing process of a table cell.
fixes #955
=> [BUGFIX] do not trim per line

packages/guides/src/DependencyInjection/GuidesExtension.php, tests/Integration/tests/configuration/config-project/expected/index.html, tests/Integration/tests/configuration/config-project/input/guides.xml, tests/Integration/tests/meta/version-from-guides-xml/input/guides.xml
symfony is trying to normalize the xml input using some logic. However in our case we want to fetch the raw value for version. But this is not possible. therefor an escape system is added by adding `'`.
=> [BUGFIX] Allow escaped version

docs/components/guidesXml.rst, docs/developers/extensions/structure.rst, docs/developers/extensions/templates.rst
Because it was a single sentence without punctuation, it was hard to
grasp that implementing the PrependExtensionInterface was optional.
Note that the lines below mention line numbers, but the line numbers are not shown on https://docs.phpdoc.org/components/guides/guides/developers/extensions/structure.html .
=> Reword paragraph

packages/guides-markdown/resources/config/guides-markdown.php, packages/guides-markdown/src/Markdown/Parsers/InlineParsers/NewLineParser.php, tests/Integration/tests/markdown/blockquote-md/expected/index.html, tests/Integration/tests/markdown/emphasis-md/expected/index.html, tests/Integration/tests/markdown/html-inline-md/expected/index.html, tests/Integration/tests/markdown/paragraph-md/expected/index.html, tests/Integration/tests/markdown/paragraph-md/input/skip, tests/Integration/tests/markdown/readme-md/expected/index.html, tests/Integration/tests/markdown/url-embedded-md/expected/index.html, tests/Integration/tests/navigation/breadcrumb/expected/page1.html, tests/Integration/tests/tables/grid-table-with-list/expected/index.html, tests/Integration/tests/toctree/toctree-glob-deep-level-3/expected/index.html
An inline break needs to be converted to a space as markdown doesn't care about linebreaks in a paragraph.
fixes #1091
=> [BUGFIX] inline break needs to convert to space

packages/guides-markdown/resources/config/guides-markdown.php, packages/guides-markdown/src/Markdown/MarkupLanguageParser.php, packages/guides-markdown/src/Markdown/ParserException.php, packages/guides-markdown/src/Markdown/Parsers/Table/TableParser.php, tests/Integration/tests/markdown/table-md/expected/index.html, tests/Integration/tests/markdown/table-md/input/skip
This patch includes basic parsing of markdown tables. Tables in markdown seem to be very limited in perspective to what ReST supports. Missing feature right now is the cell allignment, which can be applied in markdown. But not in ReST.
refs #1086
=> [FEATURE] add basic support for tables

packages/guides-cli/resources/schema/guides.xsd, packages/guides-restructured-text/src/RestructuredText/Directives/MenuDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ToctreeDirective.php, packages/guides/src/DependencyInjection/GuidesExtension.php, packages/guides/src/Handlers/ParseDirectoryHandler.php, packages/guides/src/Settings/ProjectSettings.php, tests/Integration/tests/markdown/index-name-md/expected/anotherPage.html, tests/Integration/tests/markdown/index-name-md/expected/readme.html, tests/Integration/tests/markdown/index-name-md/expected/yetAnotherPage.html, tests/Integration/tests/markdown/index-name-md/input/anotherPage.md, tests/Integration/tests/markdown/index-name-md/input/guides.xml, tests/Integration/tests/markdown/index-name-md/input/readme.md, tests/Integration/tests/markdown/index-name-md/input/yetAnotherPage.md
The index file will also be used in automatic menu building.
As oposed to setting "input-file" not only the one file mentioned will be rendererd but all files from the directory. However the name of the input file can be changed.
Some markdown projects like to change the name of the index file. For example powermail is using Readme.md as index file in every directory:
https://github.com/in2code-de/powermail/tree/master/Documentation
References #1108
=> [FEATURE] Make index file configurable

packages/guides-markdown/src/Markdown/Parsers/InlineParsers/InlineImageParser.php, packages/guides/resources/template/html/inline/image.html.twig, packages/guides/src/Nodes/Inline/ImageInlineNode.php, tests/Integration/tests/markdown/image-title-md/expected/hero-illustration.svg, tests/Integration/tests/markdown/image-title-md/expected/index.html, tests/Integration/tests/markdown/image-title-md/input/guides.xml, tests/Integration/tests/markdown/image-title-md/input/hero-illustration.svg, tests/Integration/tests/markdown/image-title-md/input/index.md
=> [FEATURE] Handle image titles in Markdown

composer.lock, packages/guides-cli/resources/schema/guides.xsd, packages/guides-markdown/src/Markdown/Parsers/HtmlParser.php, packages/guides-restructured-text/src/RestructuredText/Directives/RawDirective.php, packages/guides/composer.json, packages/guides/resources/config/guides.php, packages/guides/src/Compiler/NodeTransformers/RawNodeEscapeTransformer.php, packages/guides/src/DependencyInjection/GuidesExtension.php, packages/guides/src/Nodes/RawNode.php, tests/Integration/tests/directives/directive-raw-custom-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-custom-sanitizer/input/guides.xml, tests/Integration/tests/directives/directive-raw-custom-sanitizer/input/index.rst, tests/Integration/tests/directives/directive-raw-default-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-default-sanitizer/input/guides.xml, tests/Integration/tests/directives/directive-raw-default-sanitizer/input/index.rst, tests/Integration/tests/directives/directive-raw-no-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-no-sanitizer/input/guides.xml, tests/Integration/tests/directives/directive-raw-no-sanitizer/input/index.rst, tests/Integration/tests/markdown/html-md/input/guides.xml
This feature introduces a new compiler pass that will allow us to sanitize the html in a raw directive. We can disable the full raw usage by setting `raw_node.escape` to `true` this will block all html and displays the raw node as normal paragraph.
By default the raw directive is displayed as is and sanitized to safe html, when raw is defined as html content
```
.. raw:: html
<p>html here</p>
```
if the raw language is different than html we no nothing for now.
This pr also allows the users to define there own html sanitizer from the configuration. Example can be found in the included test.
=> [FEAT] add support for raw html sanitizers

composer.lock, packages/guides-cli/resources/schema/guides.xsd, packages/guides-markdown/src/Markdown/Parsers/HtmlParser.php, packages/guides-restructured-text/src/RestructuredText/Directives/RawDirective.php, packages/guides/composer.json, packages/guides/resources/config/guides.php, packages/guides/src/Compiler/NodeTransformers/RawNodeEscapeTransformer.php, packages/guides/src/DependencyInjection/GuidesExtension.php, packages/guides/src/Nodes/RawNode.php, tests/Integration/tests/directives/directive-raw-custom-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-custom-sanitizer/input/guides.xml, tests/Integration/tests/directives/directive-raw-custom-sanitizer/input/index.rst, tests/Integration/tests/directives/directive-raw-default-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-default-sanitizer/input/guides.xml, tests/Integration/tests/directives/directive-raw-default-sanitizer/input/index.rst, tests/Integration/tests/directives/directive-raw-no-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-no-sanitizer/input/guides.xml, tests/Integration/tests/directives/directive-raw-no-sanitizer/input/index.rst, tests/Integration/tests/markdown/html-md/input/guides.xml
This will backport the following commits from `main` to `1.x`:
- [Merge pull request #1125 from phpDocumentor/feature/sanitize-raw-html](https://github.com/phpDocumentor/guides/pull/1125)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [1.x] Merge pull request #1125 from phpDocumentor/feature/sanitize-raw-html

packages/guides-markdown/src/Markdown/Parsers/BlockQuoteParser.php, packages/guides-restructured-text/src/RestructuredText/Directives/AbstractAdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/AdmonitionDirective.php, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/AdmonitionNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/Nodes/AdmonitionNode.php, packages/guides-theme-bootstrap/resources/template/body/admonition.html.twig, packages/guides-theme-bootstrap/resources/template/body/admonitions/caution.html.twig, packages/guides-theme-bootstrap/resources/template/body/admonitions/important.html.twig, packages/guides/src/NodeRenderers/Html/AdmonitionNodeRenderer.php, packages/guides/src/Nodes/AdmonitionNode.php, tests/Integration/tests/bootstrap/bootstrap-admonition/expected/index.html, tests/Integration/tests/directives/directive-raw-custom-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-default-sanitizer/expected/index.html, tests/Integration/tests/directives/directive-raw-no-sanitizer/expected/index.html, tests/Integration/tests/markdown/admonitions-md/expected/index.html, tests/Integration/tests/markdown/admonitions-md/input/guides.xml, tests/Integration/tests/markdown/admonitions-md/input/index.md
See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
Resolves https://github.com/phpDocumentor/guides/issues/1089
=> [FEATURE] Support GitHub like Markdown Admonitions

composer.lock, packages/guides-markdown/composer.json, packages/guides-markdown/resources/config/guides-markdown.php, packages/guides-markdown/src/Markdown/MarkupLanguageParser.php, packages/guides-markdown/src/Markdown/NullNode.php, packages/guides-markdown/src/Markdown/Parsers/FrontMatter/AuthorParser.php, packages/guides-markdown/src/Markdown/Parsers/FrontMatter/Parser.php, packages/guides-markdown/src/Markdown/Parsers/FrontMatter/TitleParser.php, packages/guides-markdown/src/Markdown/Parsers/FrontMatterParser.php, tests/Integration/tests-full/markdown-full/front-matter-md/expected/index.html, tests/Integration/tests-full/markdown-full/front-matter-md/input/guides.xml, tests/Integration/tests-full/markdown-full/front-matter-md/input/index.md
Front matter format allows us to add extra meta data to documents like we can with fields in RST. This is a first setup that demos the way we can implement extra fields.
=> [FEAT] add support for front matter

.github/workflows/integrate.yaml
This will backport the following commits from `main` to `1.x`:
- [Merge pull request #1165 from phpDocumentor/dependabot/github_actions/phpDocumentor/dot-github-0.8](https://github.com/phpDocumentor/guides/pull/1165)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
=> [1.x] Merge pull request #1165 from phpDocumentor/dependabot/github_actions/phpDocumentor/dot-github-0.8

packages/guides/src/Compiler/NodeTransformers/SectionCreationTransformer.php, packages/guides/src/Nodes/DocumentNode.php, tests/Integration/tests/markdown/sections-no-level-1-md/expected/index.html, tests/Integration/tests/markdown/sections-no-level-1-md/input/guides.xml, tests/Integration/tests/markdown/sections-no-level-1-md/input/index.md
The heading level of markdown documents is not strictly 1 based. Some documents are starting with a random heading. Before those documents were rendered empty. This change fixes that behavior, headings to not longer start at level 1.
=> [FIX] make heading level dynamic

packages/filesystem/src/FileSystem.php, packages/filesystem/src/FlySystemAdapter.php, packages/filesystem/src/FlysystemV1/FlysystemV1.php, packages/filesystem/src/FlysystemV3/FlysystemV3.php
Some external libraries did rely on the usage of putResource. This method wasn't part of the new filesystem interface and was therefore breaking those implementations.
=> Fix regression on missing resource put

packages/guides/src/Files.php, packages/guides/tests/unit/FilesTest.php
File need to be ordered by location on the file system.
=> Fix natural case insensitive sort for files

packages/guides/src/Compiler/NodeTransformers/DocumentEntryRegistrationTransformer.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/GlobMenuEntryNodeTransformer.php, packages/guides/src/Nodes/DocumentTree/DocumentEntryNode.php, tests/Integration/tests-full/automatic_menu/automatic-default-menu/input/doNotInclude.rst, tests/Integration/tests/toctree/toctree-glob-level-1/input/doNotInclude.rst
Orphans are by default not meant to be in menus. Therefore they must be excluded during globbing and can only be added to a menu if they are explicitely added.
=> [BUGFIX] Ignore orphans in toctrees with globbing

packages/guides-restructured-text/src/RestructuredText/Directives/ToctreeDirective.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/ToctreeSortingTransformer.php, packages/guides/src/Nodes/DocumentTree/DocumentEntryNode.php, packages/guides/src/Nodes/Menu/MenuNode.php, tests/Integration/tests/toctree/toctree-glob-reverse/expected/index.html, tests/Integration/tests/toctree/toctree-glob-reverse/input/doNotInclude.rst, tests/Integration/tests/toctree/toctree-glob-reverse/input/index.rst, tests/Integration/tests/toctree/toctree-glob-reverse/input/page1.rst, tests/Integration/tests/toctree/toctree-glob-reverse/input/page2.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/expected/index.html, tests/Integration/tests/toctree/toctree-level-2-reversed/expected/subfolder/index.html, tests/Integration/tests/toctree/toctree-level-2-reversed/expected/subfolder2/index.html, tests/Integration/tests/toctree/toctree-level-2-reversed/input/index.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/page1.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/page2.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/subfolder/index.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/subfolder/subpage1.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/subfolder/subpage2.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/subfolder2/index.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/subfolder2/subpage1.rst, tests/Integration/tests/toctree/toctree-level-2-reversed/input/subfolder2/subpage2.rst
See also https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-option-toctree-reversed
Resolves https://github.com/phpDocumentor/guides/issues/1148
=> [FEATURE] Support :reversed: option for toctrees

packages/guides-cli/composer.json, packages/guides-cli/src/Command/Run.php, packages/guides-cli/src/Logger/SpyProcessor.php, packages/guides-cli/tests/unit/Logger/SpyProcessorTest.php, packages/guides/src/Settings/ProjectSettings.php, phpstan-baseline.neon
When the error level is set to warning on the spy errors should also be found as fail.
=> [BUGFIX] Check error level is higher
