packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DefinitionListRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/DefinitionListRuleTest.php, tests/tests/definition-list/definition-list.html
Definitions can have multiple paragraphs.
=> Fix issue with multi paragraph definitions

packages/guides-restructured-text/src/RestructuredText/Span/SpanLexer.php, packages/guides-restructured-text/src/RestructuredText/Span/SpanParser.php, packages/guides-restructured-text/tests/unit/Parser/SpanParserTest.php
- one off links are now processed correctly.
- link text is now case insenitive parsed, but still case sensitive resolved.
- fix issue with rollback on invalid link.
=> Number of fixes in link parsing

tests/tests/container-complex/container-complex.html, tests/tests/container-complex/container-complex.rst
Including a list in the content
A simple container test is already provided by #218
=> Add a complex container test

Makefile, packages/guides-restructured-text/composer.json, packages/guides/composer.json, psalm-baseline.xml
resolves https://github.com/phpDocumentor/guides/issues/215
=> Drop PHP 7.2 and 7.3 Support from guides

packages/guides-restructured-text/src/RestructuredText/Parser/LineChecker.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/CommentRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/TitleRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/TransitionRule.php, packages/guides-restructured-text/tests/unit/Parser/LineCheckerTest.php, tests/tests/comment-empty/comment-empty.html, tests/tests/comment-empty/comment-empty.rst, tests/tests/comment/comment.html, tests/tests/comment/comment.rst, tests/tests/comments-block/comments-block.html
See https://docutils.sourceforge.io/docs/user/rst/quickref.html#comments
=> Improve comment and title / separator handling

.github/workflows/integrate.yaml, .gitignore, Makefile, phpunit.xml.dist, tests/Integration/IntegrationTest.php, tests/Integration/tests/index/expected/index.html, tests/Integration/tests/index/input/index.rst
=> Introduce basic integration tests

packages/guides/src/Handlers/ParseDirectoryHandler.php, tests/Integration/tests/index_camel/expected/Index.html, tests/Integration/tests/index_camel/input/Index.rst
=> Allow CamelCase Index

tests/Integration/tests/image/expected/hero-illustration.svg, tests/Integration/tests/image/expected/images/hero2-illustration.svg, tests/Integration/tests/image/expected/index.html, tests/Integration/tests/image/expected/subfolder/subpage.html, tests/Integration/tests/image/input/hero-illustration.svg, tests/Integration/tests/image/input/images/hero2-illustration.svg, tests/Integration/tests/image/input/index.rst, tests/Integration/tests/image/input/subfolder/subpage.rst
depends on https://github.com/phpDocumentor/guides/pull/243
=> Add test that image gets copied

packages/guides/resources/template/html/guides/body/toc/toc-item.html.twig, packages/guides/resources/template/html/guides/body/toc/toc.html.twig, packages/guides/src/NodeRenderers/Html/TocEntryRenderer.php, packages/guides/src/NodeRenderers/Html/TocNodeRenderer.php
For some reason these changes were missing in #258
=> Followup: Move templates in subdirectories

packages/console/src/Command/Run.php, packages/guides/src/Compiler/Compiler.php, packages/guides/src/FileCollector.php, packages/guides/src/Metas.php, tests/Integration/IntegrationTest.php
Contains some hacks:
Metas to be reset before each run
All files are treated as new for now, disabling caching
=> Fix tests for Feature/application

packages/console/src/Command/Run.php
and Throw exception when input dir is not found
=> Use relative directory names

composer.lock, phpstan.neon
* phpstan/extension-installer (1.2.0 => 1.3.0)
* phpstan/phpstan (1.10.9 => 1.10.14)
=> Bump PHPStan

packages/guides-restructured-text/src/RestructuredText/Directives/AdmonitionDirective.php, tests/Functional/tests/admonitions/admonitions.html, tests/Functional/tests/admonitions/admonitions.rst, tests/Functional/tests/generic-admonition/generic-admonition.html, tests/Functional/tests/generic-admonition/generic-admonition.rst
=> Redefine the generic admonition

packages/guides-restructured-text/src/RestructuredText/Directives/AttentionDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/DangerDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ErrorDirective.php, packages/guides-restructured-text/src/RestructuredText/MarkupLanguageParser.php, tests/Functional/tests/admonitions/admonitions.html, tests/Functional/tests/admonitions/admonitions.rst
Also removed the `best-practice` directive, which is exclusive to Symfony.
Fixes part of #301
=> Add missing admonitions

packages/guides-restructured-text/src/RestructuredText/Directives/AbstractVersionChangeDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/DeprecatedDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/VersionAddedDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/VersionChangedDirective.php, packages/guides-restructured-text/src/RestructuredText/Nodes/VersionChangeNode.php, packages/guides-symfony/src/DependencyInjection/ReStructuredTextExtension.php, packages/guides/resources/template/html/guides/body/version-change.html.twig, tests/Functional/tests/versionchanges/versionchanges.html, tests/Functional/tests/versionchanges/versionchanges.rst
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded
Fixes #301
=> Add version change directives

packages/guides-restructured-text/src/RestructuredText/NodeRenderers/Html/AdmonitionNodeRenderer.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/DirectiveRule.php, packages/guides/resources/template/html/guides/body/admonition.html.twig, packages/guides/resources/template/html/guides/body/code.html.twig, packages/guides/src/Nodes/AbstractNode.php, tests/Integration/tests/class-option-directive/expected/index.html, tests/Integration/tests/class-option-directive/input/index.rst
=> Interpret directive option 'class'

packages/guides-symfony/resources/config/guides.php, tests/Integration/IntegrationLatexTest.php, tests/Integration/tests-latex/index/expected/index.tex, tests/Integration/tests-latex/index/input/index.rst, tests/Integration/tests-latex/index/input/skip
currently latex rendering uses HTML templates and outputs no latex.latex
=> Added skipped test for latex rendering

tests/Functional/tests/empty-p/empty-p.html
=> Unskip empty paragraph followed by literal block test

tests/Functional/tests/directive-whitespace/directive-whitespace.html
=> Unskip multiple whitespace test

packages/guides-restructured-text/src/RestructuredText/Directives/TodoDirective.php, packages/guides-symfony/resources/config/guides-restructured-text.php, tests/Functional/tests/ignored/ignored.html
They should be treated as comment
=> Ignore Todo Directives

deptrac.packages.yaml, packages/guides-graphs/composer.json, packages/guides-graphs/src/Directives/UmlDirective.php, packages/guides-symfony/resources/config/guides-restructured-text.php
- It removes a Psalm violation
- It belongs there
- It demonstrates how to register a directive in another package
TODO: Make directives independent to register in there package
=> Move UmlDirective into guides-graphs

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/FieldList/FieldListItemRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/FieldList/ProjectFieldListItemRule.php, packages/guides-restructured-text/src/RestructuredText/Parser/Productions/FieldListRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/FieldListRuleTest.php, packages/guides-symfony/resources/config/guides-restructured-text.php, packages/guides/src/Meta/ProjectMeta.php, packages/guides/src/Nodes/FieldLists/FieldListItemNode.php, packages/guides/src/Renderer/IntersphinxRenderer.php, tests/Integration/tests/inventory_json/expected/objects.inv.json, tests/Integration/tests/project-meta-global/expected/a_page.html, tests/Integration/tests/project-meta-global/expected/index.html, tests/Integration/tests/project-meta-global/expected/objects.inv.json, tests/Integration/tests/project-meta-global/input/a_page.rst, tests/Integration/tests/project-meta-global/input/index.rst, tests/Integration/tests/project-meta/expected/index.html, tests/Integration/tests/project-meta/expected/objects.inv.json, tests/Integration/tests/project-meta/input/index.rst, tests/Integration/tests/project-title/expected/index.html, tests/Integration/tests/project-title/expected/objects.inv.json, tests/Integration/tests/project-title/input/index.rst
=> Make project title and version configurable by meta field list

packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php, packages/guides/resources/template/html/guides/body/code.html.twig, packages/guides/src/Nodes/CodeNode.php, tests/Functional/tests/code-block-caption/code-block-caption.html, tests/Functional/tests/code-block-caption/code-block-caption.rst
=> Add caption to code block directive

composer.json, composer.lock, docs/usage.rst, packages/guides-cli/src/Command/Run.php, packages/guides-symfony/resources/config/guides.php, packages/guides/src/Twig/EnvironmentBuilder.php, packages/guides/src/Twig/ThemeManager.php, tests/Integration/IntegrationBootstrapTest.php, tests/Integration/IntegrationPhpDocumentorTest.php
to make themes configurable in the console application
TODO: After @wouterj introduces installable packages, themes should register themselves
resolves #291
=> Introduce ThemeManager

packages/guides-cli/src/Command/Run.php, packages/guides/src/Meta/ProjectMeta.php, tests/Integration/IntegrationBootstrapTest.php, tests/Integration/IntegrationLatexTest.php, tests/Integration/IntegrationPhpDocumentorTest.php, tests/Integration/IntegrationTest.php, tests/Integration/tests/project-title-override-warning/expected/index.html, tests/Integration/tests/project-title-override-warning/expected/logs/warning.log, tests/Integration/tests/project-title-override-warning/expected/objects.inv.json, tests/Integration/tests/project-title-override-warning/input/a_page.rst, tests/Integration/tests/project-title-override-warning/input/index.rst
this enables us, to test for warnings and errors in tests, it also improves troubleshooting for manual owners.
=> Output logs

tests/Integration/tests/sometest/index.rst
This never worked, we must have missed it in review
=> Delete incomplete test

packages/guides/src/NodeRenderers/Html/SpanNodeRenderer.php, tests/Functional/tests/literal/literal.html, tests/Functional/tests/literal/literal.rst, tests/Functional/tests/paragraph/paragraph.html, tests/Functional/tests/paragraph/paragraph.rst
=> Remove superfluous newline after inline templates

packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php, packages/guides/src/Meta/InternalTarget.php, packages/guides/src/Metas.php, packages/guides/src/Renderer/IntersphinxRenderer.php, tests/Integration/tests/inventory_ref_json/expected/objects.inv.json, tests/Integration/tests/inventory_ref_json/input/index.rst, tests/Integration/tests/inventory_ref_json/input/page1.rst, tests/Integration/tests/inventory_ref_json/input/page2.rst, tests/Integration/tests/inventory_ref_json/input/subfolder/index.rst, tests/Integration/tests/inventory_ref_json/input/subfolder/subpage1.rst, tests/Integration/tests/inventory_ref_json/input/subfolder/subpage2.rst, tests/Integration/tests/meta-data/expected/objects.inv.json, tests/Integration/tests/project-meta-global/expected/objects.inv.json, tests/Integration/tests/project-meta/expected/objects.inv.json, tests/Integration/tests/project-title-override-warning/expected/objects.inv.json, tests/Integration/tests/project-title/expected/objects.inv.json
And fix collection of internal targets
=> Add reference labels to Intersphinx Output

packages/guides/src/References/Resolver/RefResolver.php, tests/Integration/tests/anchor-to-page/expected/index.html, tests/Integration/tests/anchor-to-page/expected/objects.inv.json, tests/Integration/tests/anchor-to-page/input/index.rst, tests/Integration/tests/anchor-to-page/input/rst-overview.rst, tests/Integration/tests/anchor-to-page/input/sphinx-overview.rst
=> Use section title as default reference title

guides.xml
This way calling
```
ddev exec vendor/bin/guides docs output --theme=bootstrap
```
Works again from the mono-repository. Also this provides a configuration example
=> Register Theme Extensions

packages/guides/src/Compiler/DocumentNodeTraverser.php, packages/guides/tests/unit/Compiler/DocumentNodeTraverserTest.php
Right now exchanging a Node on leaveNode in a DocumentNodeTraverser did not change anything
=> [BUGFIX] Replace Node on leaveNode

tests/Functional/tests/interpreted-text/interpreted-text.html
=> Unskip Interpreted text

packages/guides/src/Nodes/ProjectNode.php
These are also provided by sphinx and frequently used in the TYPO3 docs
=> Introduce global variable "today" and "release"

tests/Integration/tests/variables-replace/expected/index.html, tests/Integration/tests/variables-replace/input/index.rst
=> Add a skipped Test for variable replacement

tests/Integration/tests/code-with underscore/expected/index.html, tests/Integration/tests/code-with underscore/input/index.rst, tests/Integration/tests/code-with underscore/input/skip
=> Add a skipped Test for Special signs in inline code

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/InlineRules/TextRoleRule.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/AbbreviationTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/AbstractReferenceTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/GenericTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/LiteralTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/MathTextRole.php, packages/guides-restructured-text/src/RestructuredText/TextRoles/TextRole.php, packages/guides-restructured-text/tests/unit/Parser/Productions/InlineRules/TextRoleRuleTest.php, packages/guides-restructured-text/tests/unit/TextRoles/DocReferenceTextRoleTest.php, packages/guides-restructured-text/tests/unit/TextRoles/ReferenceTextRoleTest.php
TextRoles might also need the DocumentParserContext
=> [FEATURE] Make DocumentParserContext Available in Text Roles

tests/Functional/tests/field-list-in-directive/field-list-in-directive.html, tests/Functional/tests/field-list-in-directive/field-list-in-directive.rst
=> [TASK] Add skipped test for field list in directive

composer.json, composer.lock, packages/guides-restructured-text/composer.json, packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/Directives/CsvTableDirective.php, tests/Integration/tests/table-csv-table-with-header/expected/index.html, tests/Integration/tests/table-csv-table-with-header/input/index.rst, tests/Integration/tests/table-csv-table-with-header/input/test.csv, tests/Integration/tests/table-csv-table-with-markup/expected/index.html, tests/Integration/tests/table-csv-table-with-markup/input/index.rst, tests/Integration/tests/table-csv-table-with-markup/input/test.csv, tests/Integration/tests/table-csv-table/expected/index.html, tests/Integration/tests/table-csv-table/input/index.rst, tests/Integration/tests/table-csv-table/input/test.csv
Add csv table directive, this allows users to import a csv as table.
=> [Feature]: Add csv table directive

packages/guides-restructured-text/src/RestructuredText/Parser/Productions/AnnotationRule.php, packages/guides-restructured-text/tests/unit/Parser/Productions/AnnotationRuleTest.php, packages/guides/resources/template/html/body/annotation-list.html.twig, packages/guides/src/DependencyInjection/Compiler/NodeRendererPass.php, packages/guides/src/Nodes/AnnotationListNode.php, tests/Integration/tests/footnote-list/expected/index.html, tests/Integration/tests/footnote-list/input/skip
resolves https://github.com/phpDocumentor/guides/issues/447
=> [BUGFIX] Handle footnotes and citations ins lists

packages/guides/src/ReferenceResolvers/ExternalReferenceResolver.php, tests/Integration/tests/hyperlink-to-anchor/expected/index.html, tests/Integration/tests/hyperlink-to-anchor/input/index.rst
=> [BUGFIX] Allow hyperlinks to anchors

packages/guides/resources/config/guides.php, packages/guides/src/ReferenceResolvers/AnchorReferenceResolver.php, packages/guides/src/ReferenceResolvers/EmailReferenceResolver.php, packages/guides/src/ReferenceResolvers/ExternalReferenceResolver.php, tests/Integration/tests/hyperlink-to-email/expected/index.html, tests/Integration/tests/hyperlink-to-email/input/index.rst
I moved each of these checks into their own ReferenceResolver as it does not really make sense to check for anchors in an ExternalURLResolver
=> [BUGFIX] Allow Emails in anonymous links

guides.xml, packages/guides/src/DependencyInjection/GuidesExtension.php, tests/Integration/tests/index-html-only/expected/index.html, tests/Integration/tests/index-html-only/input/guides.xml, tests/Integration/tests/index-html-only/input/index.rst
And use html, intersphinx as default output formats
=> [BUGFIX] Treat single output formats as array

packages/guides-code/resources/config/guides-code.php, packages/guides-code/src/Code/DependencyInjection/CodeExtension.php, packages/guides-code/src/Code/Highlighter/Highlighter.php, packages/guides-code/src/Code/Twig/CodeExtension.php, packages/guides-code/tests/unit/Highlighter/HighlighterTest.php
Couple fixes while testing out the new guides-code extension in the Symfony docs.
=> Highlighter improvements

.github/workflows/documentation.yml, Makefile, packages/guides-cli/src/Command/Run.php, tests/Integration/IntegrationTest.php
This way it can be set indepenently from the input
=> [!!!][TASK] Make output an option instead of argument

phpstan-baseline.neon, phpstan.neon
I put all errors in the baseline for now, we can reduce them by and by but will be alerted on new ones now.
=> [TASK] Add forgotten paths to phpstan

packages/guides-restructured-text/resources/config/guides-restructured-text.php
these have been removed a while back
=> [BUGFIX] Remove non-existent directives from DI

composer.json, composer.lock, packages/guides/composer.json
=> [TASK] bump league uri depenciency

packages/guides/src/DependencyInjection/GuidesExtension.php
=> Fix undefined array key when project title not defined

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/resources/template/html/body/directive/only.html.twig, packages/guides-restructured-text/resources/template/latex/body/directive/only.tex.twig, packages/guides-restructured-text/src/RestructuredText/NodeRenderers/LaTeX/GeneralDirectiveNodeRenderer.php, tests/Integration/tests/directives/directive-only/expected/index.html, tests/Integration/tests/directives/directive-only/expected/index.tex, tests/Integration/tests/directives/directive-only/input/guides.xml, tests/Integration/tests/directives/directive-only/input/index.rst
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#including-content-based-on-tags
resolves https://github.com/phpDocumentor/guides/issues/689
=> [FEATURE] Introduce only directive

tests/Integration/tests/body-elements/line-blocks/expected/index.html, tests/Integration/tests/body-elements/line-blocks/input/index.rst, tests/Integration/tests/body-elements/line-blocks/input/skip
See for example https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
=> [TASK] At skipped tests for line blocks

packages/guides-cli/bin/guides
Enviroment variable SHELL_VERBOSITY can be used or `-vvv` to echo the used config files
=> [TASK] add debug level echo for config

packages/guides-graphs/resources/config/guides-graphs.php, packages/guides-graphs/src/Graphs/Renderer/TestRenderer.php, packages/guides-graphs/src/Graphs/Twig/UmlExtension.php, tests/Integration/tests/graphs/plantuml-external/expected/Plantuml/index.html, tests/Integration/tests/graphs/plantuml-external/expected/index.html, tests/Integration/tests/graphs/plantuml-external/input/guides.xml, tests/Integration/tests/graphs/plantuml-inline/expected/index.html, tests/Integration/tests/graphs/plantuml-inline/input/guides.xml
We cannot rely on external services in our tests. So make sure the test-renderer is used to test uml rendering.
=> !!![TASK] use dummy test renderer

psalm-baseline.xml
This happens automatically whenever you run "make pre-commit" right now
=> [BUGFIX] Update version in psalm baseline

packages/guides-restructured-text/src/RestructuredText/Directives/FigureDirective.php, packages/guides/resources/template/html/body/figure.html.twig, tests/Functional/tests/figure/figure.html, tests/Functional/tests/figure/figure.rst
Found some small issues when checking all skipped test in the Symfony testsuite. See commit messages for more information :)
=> Two minor figure bugs

composer.json, composer.lock, packages/guides-restructured-text/src/RestructuredText/Parser/InlineLexer.php, packages/guides-restructured-text/tests/benchmarks/InlineLexerBench.php, phpbench.json
By moving the match to the top of the method we can cut down the usage of the more expensive preg_match calls in this method. This gives the lexer a boost of about 60%. It's not a major step forward as the lexer is already very fast.
=> Add improvement in lexer performance

packages/guides/resources/config/guides.php, packages/guides/src/Interlink/DefaultInventoryLoader.php, packages/guides/src/Interlink/DefaultInventoryRepository.php, packages/guides/src/Interlink/InventoryLoader.php, packages/guides/src/Interlink/InventoryRepository.php, packages/guides/tests/unit/Interlink/InventoryLoaderTest.php
So that they can be exchanged by DI, for example to load inventories from composer
=> [TASK] Introduce Interfaces for Inventory loading

packages/guides/src/Event/PostParseDocument.php, packages/guides/src/Event/PostParseProcess.php, packages/guides/src/Event/PostRenderDocument.php, packages/guides/src/Event/PostRenderProcess.php, packages/guides/src/Event/PreParseDocument.php, packages/guides/src/Event/PreParseProcess.php, packages/guides/src/Event/PreRenderDocument.php, packages/guides/src/Event/PreRenderProcess.php, packages/guides/src/Handlers/ParseDirectoryHandler.php, packages/guides/src/Handlers/RenderHandler.php, packages/guides/tests/unit/Event/PreRenderProcessTest.php, phpstan.neon
Additionally improve class comments for events and create a unit test
=> [FEATURE] Introduce missing events

packages/guides-graphs/src/Graphs/Renderer/PlantumlRenderer.php
When the process fails with an exception the rendering should not stop. We just want to continue to the rendering.
=> [FIX] Catch exception to prevent crash

packages/guides-restructured-text/src/RestructuredText/Directives/ContentsDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/MenuDirective.php, packages/guides-restructured-text/src/RestructuredText/Directives/ToctreeDirective.php, packages/guides-restructured-text/src/RestructuredText/Toc/ToctreeBuilder.php, packages/guides/src/Compiler/NodeTransformers/ContentMenuNodeWithSectionEntryTransformer.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeAddEntryTransformer.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeAddSubDocumentsTransformer.php, packages/guides/src/Compiler/Passes/GlobalMenuPass.php, packages/guides/src/NodeRenderers/Html/BreadCrumbNodeRenderer.php, packages/guides/src/NodeRenderers/Html/MenuEntryRenderer.php, packages/guides/src/Nodes/Menu/ExternalMenuEntryNode.php, packages/guides/src/Nodes/Menu/InternalMenuEntryNode.php, packages/guides/src/Nodes/Menu/MenuDefinitionLineNode.php, packages/guides/src/Nodes/Menu/MenuEntryNode.php, packages/guides/src/Nodes/Menu/MenuNode.php, packages/guides/src/Nodes/Menu/ParsedMenuEntryNode.php, packages/guides/src/Nodes/TitleNode.php, packages/guides/src/Renderer/UrlGenerator/AbstractUrlGenerator.php, packages/guides/src/Renderer/UrlGenerator/UrlGeneratorInterface.php, packages/guides/tests/unit/Compiler/DocumentNodeTraverserTest.php, packages/guides/tests/unit/Compiler/NodeTransformers/MenuNodeAddSubDocumentsTransformerTest.php, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-linktargets/expected/index.html, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-linktargets/input/guides.xml, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-linktargets/input/index.rst, tests/Integration/tests-full/bootstrap/bootstrap-menu-external-linktargets/input/page1.rst, tests/Integration/tests/toctree/toctree-external-linktargets/expected/index.html, tests/Integration/tests/toctree/toctree-external-linktargets/input/index.rst, tests/Integration/tests/toctree/toctree-external-linktargets/input/page1.rst
This change is breaking if someone extended the menu nodes or build their own ones
=> [FEATURE] Support Menu entries with overriden titles and external urls

packages/guides-graphs/src/Graphs/Renderer/DiagramRenderer.php, packages/guides-graphs/src/Graphs/Renderer/PlantumlRenderer.php, packages/guides-graphs/src/Graphs/Renderer/PlantumlServerRenderer.php, packages/guides-graphs/src/Graphs/Renderer/TestRenderer.php, packages/guides-graphs/src/Graphs/Twig/UmlExtension.php
For this we have to pass the rendercontext to the DiagramRenderer, a breaking change if the interface was implemented externally.
=> !!![FEATURE] Improve Plantuml debug output

tests/Integration/tests/meta/version-from-guides-xml/expected/index.html, tests/Integration/tests/meta/version-from-guides-xml/input/guides.xml, tests/Integration/tests/meta/version-from-guides-xml/input/index.rst, tests/Integration/tests/meta/version-from-guides-xml/input/skip
references https://github.com/phpDocumentor/guides/issues/829
=> [TASK] Integration test version with trailing zero

tests/Integration/tests/markdown/sections-md/expected/index.html, tests/Integration/tests/markdown/sections-md/input/guides.xml, tests/Integration/tests/markdown/sections-md/input/index.md, tests/Integration/tests/markdown/sections-md/input/skip, tests/Integration/tests/meta/version-from-guides-xml/expected/index.html, tests/Integration/tests/sections/expected/index.html, tests/Integration/tests/sections/input/index.rst
references https://github.com/phpDocumentor/guides/issues/842
=> [TASK] Add tests for sections in rst and md

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/Directives/SectionauthorDirective.php, packages/guides/resources/template/html/body/author.html.twig, packages/guides/resources/template/html/template.php, packages/guides/src/Nodes/AuthorNode.php, tests/Integration/tests/body-elements/line-blocks/expected/index.html, tests/Integration/tests/directives/sectionauthor/expected/index.html, tests/Integration/tests/directives/sectionauthor/input/index.rst, tests/Integration/tests/directives/youtube/expected/index.html, tests/Integration/tests/images/figure-relative/expected/index.html, tests/Integration/tests/images/figure-relative/expected/subfolder/subpage.html, tests/Integration/tests/images/image-absolute/expected/index.html, tests/Integration/tests/images/image-relative/expected/index.html, tests/Integration/tests/images/image-relative/expected/subfolder/subpage.html
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#meta-information-markup
resolves https://github.com/phpDocumentor/guides/issues/847
=> [FEATURE] Add Meta-information markup

packages/guides/src/Renderer/InterlinkObjectsRenderer.php, tests/Integration/tests/anchor/anchor-to-page/expected/objects.inv.json, tests/Integration/tests/confval/expected/objects.inv.json, tests/Integration/tests/interlink/inventory_json/expected/objects.inv.json, tests/Integration/tests/meta/project-title/expected/objects.inv.json, tests/Integration/tests/option/expected/objects.inv.json
Sphinx and even our library itself expect empty values to be a string with "-". Null causes errors
=> [BUGFIX] Replace null with "-" in objects.inv.json

docs/installation.rst
Or they will not be attached to the correct section
=> [BUGFIX] Move anchors above headlines

psalm-baseline.xml
There have been changes with the lastes updates it seems
=> [TASK] Update Psalm Baseline

.github/workflows/documentation.yml, Makefile, docs/cli/index.rst, docs/reference/restructuredtext/text-roles.rst
=> [TASK] Use Fail-On-Log for our docs again

packages/guides-restructured-text/resources/template/html/body/directive/hlist.html.twig, tests/Integration/tests/lists/lists-hlist/expected/index.html, tests/Integration/tests/lists/lists-hlist/input/index.rst, tests/Integration/tests/tables/list-table-directive/expected/index.html
=> [FEATURE] Support hlist directive

packages/guides-restructured-text/resources/config/guides-restructured-text.php, packages/guides-restructured-text/src/RestructuredText/Directives/MathDirective.php, packages/guides/resources/template/html/body/math.html.twig, packages/guides/resources/template/html/template.php, packages/guides/src/Nodes/MathNode.php, tests/Integration/tests/directives/directive-math/expected/index.html, tests/Integration/tests/directives/directive-math/input/index.rst, tests/Integration/tests/tables/list-table-directive/expected/index.html
=> [FEATURE] Support math directive

packages/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php, tests/Integration/tests/code/parsed-literal-block/expected/index.html, tests/Integration/tests/code/parsed-literal-block/input/index.rst, tests/Integration/tests/tables/list-table-directive/expected/index.html
=> [FEATURE] Support Parsed Literal Block

packages/guides-restructured-text/src/RestructuredText/Directives/ContentsDirective.php, packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/ContentsMenuEntryNodeTransformer.php, packages/guides/src/Nodes/DocumentTree/DocumentEntryNode.php, packages/guides/src/Nodes/DocumentTree/SectionEntryNode.php, packages/guides/src/Nodes/Menu/ContentMenuNode.php, tests/Integration/tests/navigation/contents/contents-local/expected/index.html, tests/Integration/tests/navigation/contents/contents-local/input/index.rst
=> [FEATURE] Add local option to contents directive

packages/guides-graphs/src/Graphs/Renderer/PlantumlServerRenderer.php, packages/guides-restructured-text/tests/unit/Parser/Productions/RuleTestCase.php, packages/guides-restructured-text/tests/unit/Parser/Productions/SectionRuleTest.php, tests/Integration/tests/graphs/plantuml-server-error/expected/logs/warning.log, tests/Integration/tests/graphs/plantuml-server-error/input/guides.xml
=> [FIX] catch transport exception when host can not be reached

packages/guides-restructured-text/src/RestructuredText/Directives/ConfvalDirective.php, tests/Integration/tests/confval/confval-no-title/expected/index.html, tests/Integration/tests/confval/confval-no-title/expected/logs/warning.log, tests/Integration/tests/confval/confval-no-title/input/index.rst, tests/Integration/tests/graphs/plantuml-server-error/expected/index.html
resolves https://github.com/phpDocumentor/guides/issues/983
=> [BUGFIX] Warn when a directive has not title

packages/guides/resources/config/guides.php, packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php, packages/guides/src/Nodes/SectionNode.php, packages/guides/src/ReferenceResolvers/TitleReferenceResolver.php, tests/Integration/tests/anchor/anchor-to-page/expected/objects.inv.json, tests/Integration/tests/confval/confval-name/expected/objects.inv.json, tests/Integration/tests/confval/confval-noindex/expected/objects.inv.json, tests/Integration/tests/confval/confval-warning/expected/objects.inv.json, tests/Integration/tests/interlink/inventory_json/expected/objects.inv.json, tests/Integration/tests/interlink/inventory_ref_json/expected/objects.inv.json, tests/Integration/tests/meta/config-file/expected/objects.inv.json, tests/Integration/tests/meta/meta-data/expected/objects.inv.json, tests/Integration/tests/meta/project-meta-global/expected/objects.inv.json, tests/Integration/tests/meta/project-meta/expected/objects.inv.json, tests/Integration/tests/meta/project-title-override-warning/expected/objects.inv.json, tests/Integration/tests/meta/project-title/expected/objects.inv.json, tests/Integration/tests/meta/settings/expected/objects.inv.json, tests/Integration/tests/numeral-rst/expected/objects.inv.json, tests/Integration/tests/option/expected/objects.inv.json, tests/Integration/tests/references/reference-to-anchor/expected/anotherPage.html, tests/Integration/tests/references/reference-to-anchor/expected/index.html, tests/Integration/tests/references/reference-to-anchor/expected/objects.inv.json, tests/Integration/tests/references/reference-to-anchor/expected/yetAnotherPage.html, tests/Integration/tests/references/reference-to-anchor/input/anotherPage.rst, tests/Integration/tests/references/reference-to-anchor/input/guides.xml, tests/Integration/tests/references/reference-to-anchor/input/index.rst, tests/Integration/tests/references/reference-to-anchor/input/yetAnotherPage.rst
Resolves https://github.com/phpDocumentor/guides/issues/970
=> [BUGFIX] Prefere anchors over titles in references

packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardFooterDirective.php, packages/guides/resources/template/html/inline/link.html.twig, tests/Integration/tests/bootstrap/bootstrap-card-group/expected/index.html, tests/Integration/tests/bootstrap/bootstrap-card-group/input/index.rst, tests/Integration/tests/bootstrap/bootstrap-cards/expected/index.html
=> [BUGFIX] Display value of card-footer,

packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php, packages/guides/src/Exception/DuplicateLinkAnchorException.php, packages/guides/src/Nodes/ProjectNode.php, tests/Integration/tests/anchor/anchor-duplicate-warning/expected/index.html, tests/Integration/tests/anchor/anchor-duplicate-warning/expected/logs/warning.log, tests/Integration/tests/anchor/anchor-duplicate-warning/input/index.rst, tests/Integration/tests/anchor/anchor-duplicate-warning/input/page.rst
=> [TASK] Warn about duplicate anchors

packages/guides-restructured-text/src/RestructuredText/Directives/ConfvalDirective.php, packages/guides-restructured-text/src/RestructuredText/Parser/Directive.php, packages/guides-restructured-text/src/RestructuredText/Parser/DirectiveOption.php, tests/Integration/tests/confval/confval-name/expected/index.html, tests/Integration/tests/confval/confval-name/expected/objects.inv.json, tests/Integration/tests/confval/confval-name/input/index.rst
It was alway defaulting to true if the option was set.
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/554
=> [BUGFIX] Fix confval required

packages/guides-restructured-text/src/RestructuredText/Directives/MenuDirective.php, tests/Integration/tests/navigation/breadcrumb/expected/page1.html, tests/Integration/tests/navigation/menu-level-3/input/level-1-1/level-2-2/subpage1.rst, tests/Integration/tests/navigation/menu-level-3/input/level-1-2/index.rst, tests/Integration/tests/navigation/menu-level-3/input/level-1-2/subpage1.rst, tests/Integration/tests/navigation/menu-level-3/input/page1.rst, tests/Integration/tests/navigation/menu-relative/input/level-1-1/level-2-2/subpage1.rst, tests/Integration/tests/navigation/menu-relative/input/level-1-2/subpage1.rst, tests/Integration/tests/navigation/menu-relative/input/page1.rst
Just like toctree menu should support sub-titles
=> [FEATURE] enable subtitles on menus

tests/Integration/tests/markdown/url-embedded-md/expected/index.html, tests/Integration/tests/markdown/url-embedded-md/input/guides.xml, tests/Integration/tests/markdown/url-embedded-md/input/index.md, tests/Integration/tests/markdown/url-embedded-md/input/skip
=> [TASK] Add incomplete tests for Embedded URLS in Markdown

tests/Integration/tests/markdown/table-md/expected/index.html, tests/Integration/tests/markdown/table-md/input/guides.xml, tests/Integration/tests/markdown/table-md/input/index.md, tests/Integration/tests/markdown/table-md/input/skip
See https://github.com/phpDocumentor/guides/issues/1086
=> [TASK] Add incomplete tests for MD table

tests/Integration/tests/markdown/paragraph-md/expected/index.html, tests/Integration/tests/markdown/paragraph-md/input/guides.xml, tests/Integration/tests/markdown/paragraph-md/input/index.md, tests/Integration/tests/markdown/paragraph-md/input/skip
=> [TASK] Add incomplete tests for paragraph with whitespace issues

packages/guides/resources/template/html/inline/image.html.twig, tests/Integration/tests/markdown/image-md/expected/index.html, tests/Integration/tests/markdown/image-md/input/skip
=> [BUGFIX] use asset plugin to copy images

Makefile
To make sure the copied files are up to date
=> [TASK] Rerun integration tests before integration baseline update

tests/Integration/tests/markdown/warning-md/expected/index.html, tests/Integration/tests/markdown/warning-md/input/guides.xml, tests/Integration/tests/markdown/warning-md/input/index.md
=> [TASK] Add incomplete tests for warning in MarkDown

packages/guides/src/Twig/AssetsExtension.php, tests/Integration/tests/markdown/image-path-relative-md/expected/dir1/dir2/index.html, tests/Integration/tests/markdown/image-path-relative-md/expected/dir1/dir2/somePage.html, tests/Integration/tests/markdown/image-path-relative-md/expected/dir1/index.html, tests/Integration/tests/markdown/image-path-relative-md/expected/images/hero-illustration.svg, tests/Integration/tests/markdown/image-path-relative-md/expected/index.html, tests/Integration/tests/markdown/image-path-relative-md/input/dir1/dir2/index.md, tests/Integration/tests/markdown/image-path-relative-md/input/dir1/dir2/somePage.md, tests/Integration/tests/markdown/image-path-relative-md/input/dir1/index.md, tests/Integration/tests/markdown/image-path-relative-md/input/guides.xml, tests/Integration/tests/markdown/image-path-relative-md/input/images/hero-illustration.svg, tests/Integration/tests/markdown/image-path-relative-md/input/index.md, tests/Integration/tests/markdown/image-path-relative-md/input/somePage.md
This will solve the situations containing relative urls.
=> [FIX] use canonicalUrl to fetch images

packages/guides/src/Event/PostParseDocument.php, packages/guides/src/Handlers/ParseFileHandler.php
We should allow post parse events to change the document.
=> [FEAT] Allow post parse mutations

packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php, tests/Integration/tests/anchor/anchor-to-page/expected/objects.inv.json, tests/Integration/tests/images/image-target/expected/index.html, tests/Integration/tests/interlink/inventory_ref_json/expected/objects.inv.json, tests/Integration/tests/references/reference-to-anchor/expected/objects.inv.json
=> [BUGFIX] Make title links link to the first anchor of a section

packages/guides-restructured-text/src/RestructuredText/TextRoles/DefaultTextRoleFactory.php, packages/guides-restructured-text/tests/unit/TextRoles/DefaultTextRoleFactoryTest.php
=> FEAT: make textroles case insentive

packages/guides-markdown/src/Markdown/Parsers/ListBlockParser.php, tests/Integration/tests/lists/numbered-lists-defined/expected/index.html, tests/Integration/tests/lists/numbered-lists-defined/input/index.rst, tests/Integration/tests/markdown/lists-md/expected/index.html, tests/Integration/tests/markdown/lists-md/input/index.md
Resolves: https://github.com/phpDocumentor/guides/issues/1243
=> [BUGFIX] Numbered lists should continue numbering
